---
title: "Reliability and accuracy"
---

::: {.callout-note appearance="simple"}
This is a work in progress that is currently undergoing heavy technical editing and copy-editing
:::

## Terminology 

Disease severity, especially when expressed in percent area diseased, is acknowledged as a more difficult and less time- and cost-effective plant disease variable to obtain, especially when assessed visually. However, errors may occur even when assessing a more objective measure such as incidence. This is the case when an incorrect assignment or confusion of symptoms occur. In either case, the quality of the assessment of any disease variable is very important and should be gauged in the studies. Several terms can be used when evaluating the quality of disease assessments, including reliability, precision, accuracy or agreement.

-   **Reliability**: The extent to which the same estimates or measurements of diseased specimens obtained under different conditions yield similar results. There are two types. The inter-rater reliability (or reproducibility) is a measure of consistency of disease assessment across the same specimens between raters or devices. The intra-rater reliability (or repeatability) measures consistency by the same rater or instrument on the same specimens (e.g. two assessments in time by the same rater). 

-   **Precision:** A statistical term to express the measure of variability of the estimates or measurements of disease on the same specimens obtained by different raters or instruments. However, reliable or precise estimates (or measurements) are not necessarily close to an actual value, but precision is a component of accuracy or agreement.

-   **Accuracy or agreement**: These two terms can be treated as synonymous in plant pathological research. They refer to the closeness (or concordance) of an estimate or measurement to the actual severity value for a specimen on the same scale. Actual values may be obtained using various methods, against which estimates or measurements using an experimental assessment method are compared.

## Statistical tests

The assessment of the quality of estimates or measures is usually performed using statistical summaries or tests to evaluate 

### Reliability

### Precision

### Accuracy or agreement




