# Epidemic data

## Introduction

In order to study epidemics in both time and space, we first need a measurement of disease quantity. The study of plant disease quantification is known as Phytopathometry, a well-established branch of phytopathology tasked with the science of disease measurement [@bock2021].

Historically, disease quantification has been performed visually, but advances in both imaging and remote sensing technologies have directly impacted phytopathometry during the last several decades. Therefore, the quantity of disease can be obtained via estimation (visually by human eye) or measurement (sensor or digital technologies). While measuring disease is an objective task, visual assessment is largely subjective and as such known to vary among individuals. This is simply because humans possess different inherent ability, vary in the degree or training to assess disease severity or are more or less affected by the method in use (e.g. scales).

## Terminology

Disease is estimated or measured on a specimen in a population, or on a sample of specimens drawn from a population. The specimen can be a plant organ, an individual plant, a group of plants, a field or a farm. A general term used to refer to the quantity of disease expressed by any means is **disease intensity**. A primary task when assessing disease is to classify each specimen in a sample as diseased or not diseased. Such binary (yes/no) assessment may be sufficient to determine disease intensity when the goal is to assess, for example, the number or proportion of diseased specimens in a sample or a population of specimens.

Disease measured based on counts of specimens is defined as disease **incidence** or disease **prevalence**. Incidence is commonly used to refer to within field scale considering whole plants or their organs as the observational units, while prevalence is commonly used when referring to the proportion or number of fields or farms with diseased plants in a large production area or region.

In many cases we need to ascertain the *degree to which a specimen is diseased*, which is the definition of disease **severity**. In some textbooks and glossaries severity is defined restrictively as the proportion of the unit that is symptomatic, but a revised and broader concept of disease severity encompasses other metrics including lesion counts, ordinal scales with classes defined based on either the percentage scale or descriptions of symptoms (mild to severe, particularly applicable to systemic diseases) [@bock2021].
