# Welcome {.unnumbered}

**R for Plant Disease Epidemiology** (R4PDE) is a dynamic online book rooted in the teachings of the annual graduate course, FIP 602 - Plant Disease Epidemiology, a key part of the curriculum in the [Graduate Program in Plant Pathology](http://www.dfp.ufv.br/grad/) at Universidade Federal de Viçosa.

Designed for those passionate about studying and modeling plant disease epidemics with [R](https://www.r-project.org/), the book offers an exploration of diverse methods for describing, visualizing, and analyzing epidemic data collected over time and space. Readers should ideally have a foundational knowledge of R to best utilize the examples.

However, R4PDE is not a resource for learning data science through R, as there are already well-established books such as [R for data science](https://r4ds.had.co.nz/) for that purpose. This book draws on multiple sources, but in certain sections, it utilizes data and replicates (with permission) some of the analyses (presented in SAS codes) from [*The Study of Plant Disease Epidemics*](https://apsjournals.apsnet.org/doi/book/10.1094/9780890545058) [@madden2007], a highly recommended textbook for anyone wishing to delve deeply into plant disease epidemiology.

A mix of general and specific R packages are utilized to conduct common plant disease epidemiology data analysis, notably [{epifitter}](https://alvesks.github.io/epifitter/) and [{epiphy}](https://chgigot.github.io/epiphy/), both designed by plant pathologists. In conjunction with this book, a new R package [{r4pde}](https://github.com/emdelponte/r4pde) has been developed and can be installed from GitHub using:

    #install.packages("remotes")
    remotes::install_github("emdelponte/r4pde")

This online book is frequently updated and edited. This website is free to use, licensed under a [Creative Commons licence](https://creativecommons.org/licenses/by-nc/4.0/), and the code for all analyses can be found on [GitHub](https://github.com/emdelponte/epidemiology-R). The website is hosted by https://www.netlify.com/. Contributions are subject to a [Contributor Code of Conduct](https://contributor-covenant.org/version/2/0/CODE_OF_CONDUCT.html), and by contributing, you agree to adhere to its terms.

## Acknowledgements

To [Helen Pennington](https://www.hgpenningtonart.co.uk/) for allowing me to use her painting of coffee leaf rust as book cover. Also to those who have contributed fixes and improvements via pull request or other form of contact: Adam Sparks ([\@adamhsparks](https://github.com/adamhsparks)), Remco Stam ([\@remco-stam](https://github.com/remco-stam)), Tiago Olivoto ([\@TiagoOlivoto](https://github.com/TiagoOlivoto)), Monalisa De Cól ([\@Monalisacdc](https://github.com/Monalisacdc)), and Juan Edwards Molina ([\@juanchiem](https://github.com/juanchiem)).
