---
title: "Modeling Plant Epidemics in R "
description: |
  Prof. [Emerson Del Ponte](https://emersondelponte.netlify.app/)<br>
  Departamento de Fitopatologia<br>
  Universidade Federal de Viçosa<br><br>
site: distill::distill_website
---

# About

Modeling Plant Disease epidemics in R is a tutorial prepared to support several lectures I've given as Guest Lecturer for the **Plant Disease Epidemiology** course offered to students of the [Professional Masters in Plant Health](https://planthealth.upv.es/) in Sustainable Cropping Systems. These materials have been used in my graduate course on Plant Disease Epidemiology FIP 602 offered every year by the [Graduate Program in Plant Pathology](http://www.dfp.ufv.br/grad/) of the Universidade Federal de Viçosa.

# Modules

This is a work in progress and new modules will be added when ready. Currently, the following topics have been covered:

-   Temporal analysis

    -   [Population dynamics models](temporal-population-models.html)

    -   [Fitting models to actual epidemics](temporal-fitting-models.html)
