---
title: "Untitled"
author: "Emerson"
date: "2022-10-12"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}

# https://bsppjournals.onlinelibrary.wiley.com/doi/10.1111/j.1365-3059.2006.01393.x
dat3 <- tibble::tribble(
  ~t, ~y,
12.1, 0.00,
15.1, 0.1,
20.0, 0.5,
25.0, 1.2,
30.0, 1.5,
35.0, 1.2,
40.0, 0.1
)



# beta generalizada
# Y=B1((X-B2)^B4)((B3-X)^B5)
library(minpack.lm)
fit <- nlsLM(y ~ b1*((t - b2 )^b4)*((b3 - t)^b5),
             start = list(b1 = 0,
                          b2 = 10, 
                          b3 = 40, 
                          b4 = 1.5, 
                          b5 = 1),
             algorithm = "port",
             data = dat3)
fit$m$getAllPars()


b1 <- fit$m$getAllPars()[1]
b2 <- fit$m$getAllPars()[2]
b3 <- fit$m$getAllPars()[3]
b4 <- fit$m$getAllPars()[4]
b5 <- fit$m$getAllPars()[5]
t <- seq(10,45, 0.1)
y <- b1*((t - b2 )^b4)*((b3 - t)^b5)
dat <- data.frame(t, y)

library(tidyverse)
dat |> 
  ggplot(aes(t, y))+
  geom_line()+
  geom_point(data = dat3, aes(t, y))

```

```{r}
library(digitize)
#dat4 <- digitize("imgs/wetness_severity.png")
#dat4 

dat4 <- tibble::tribble(
  ~x, ~y,
0.01311475, -0.02197802,
  4.05245902,  0.50000000,
  8.09180328 , 0.81318681,
 11.92131148 , 1.50549451,
 16.01311475,  1.26923077,
 20.10491803 , 2.10439560,
 23.93442623 , 1.45604396
)
library(minpack.lm)
fitm <- nlsLM(y ~ c + (d-c)*(1-exp(-x/e)), 
              start = list(c = 0.5,
                           d = 3,
                           e = 1),
                           data = dat4)

library(drc)
drm1 <- drm(y ~x, data = dat4, fct = AR.2())
drm1
plot(drm1, log = "")
predict(drm1)
```

```{r}

t <- rep(1:40,40)
HW <- rep(1:40, each = 40)
b1 <- fit$m$getAllPars()[1]
b2 <- fit$m$getAllPars()[2]
b3 <- fit$m$getAllPars()[3]
b4 <- fit$m$getAllPars()[4]
b5 <- fit$m$getAllPars()[5]

c <-  fitm$m$getAllPars()[1]
d <- fitm$m$getAllPars()[2]
e <- fitm$m$getAllPars()[3]
dis <- (b1*(t - b2 )^b4)*((b3 - t)^b5) * (c + (d-c)*(1-exp(-HW/e)))
validation <- data.frame(t, HW, dis)
```


```{r}
library(ggplot2)
library(geomtextpath)
ggplot(validation, aes(t, HW, z = dis)) + 
  geom_contour_filled(bins = 8, alpha = 0.7) + 
  geom_textcontour(bins = 8, size = 2.5, padding = unit(0.05, "in")) + 
  theme_minimal() +
  theme(legend.position = "none")+
  ylim(0, 40)+
  labs(y = "Wetness duration (hours)", x = "Temperature (Celcius)")
```


```{r}

t <- rep(5:30,30)
W <- rep(5:30, each = 30)
dis2 <- -1.70961637 + 0.02886124*t + 0.04943329*W + 0.00868240*t*W - 0.00236213*W^2 - 0.00023788*(t^2)*W 
dis2 <- 10^dis2  
validation2 <- data.frame(t, W, dis2)

  

```


```{r}
library(ggplot2)
library(geomtextpath)
ggplot(validation2, aes(t, W, z = dis2)) + 
  geom_contour_filled(bins = 8, alpha = 0.7) + 
  geom_textcontour(bins = 8, size = 2.5, padding = unit(0.05, "in")) + 
  theme_minimal() +
  theme(legend.position = "none")+
  ylim(0, 30)+
  labs(y = "Wetness duration (hours)", x = "Temperature (Celcius)")
```

```{r}

# https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0193813
```

