---
title: "Disease modeling"
editor: visual
editor_options: 
  chunk_output_type: inline
bibliography: references.bib
---

## Introduction

Plant disease modeling is a crucial tool for predicting disease dynamics and informing management decisions. By leveraging models, researchers and practitioners can anticipate disease outbreaks, assess potential risks, and implement timely interventions to mitigate losses [@savary2018; @rossi2010a].

Plant disease models integrating plant, disease, and environmental - in most cases weather-based variables - factors have been developed since the mid-1900s (See recent review by @gonzález-domínguez2023 ). Dynamic modeling of disease epidemics gained traction in the early 1960s with foundational work by Van der Plank and Zadoks, setting the stage for future advancements. Since then, researchers have contributed extensively to model development [@dewolf2007]. A systematic map by @fedele2022a identified over 750 papers on plant disease models, primarily aimed at understanding system interactions (n = 680). This map revealed that while most models focus on system understanding, fewer are devoted to tactical management (n = 40), strategic planning (n = 38), or scenario analysis (n = 9).

As to model development, we can classify the models into two main groups based on the approach taken [@gonzález-domínguez2023]: Empirical or mechanistic approaches, which differ fundamentally in their basis, complexity and application.

**Empirical models**, which emerged in the mid-20th century, rely on data-driven statistical relationships between variables collected under varying field conditions. These models often lack cause-effect understanding, making them less robust and requiring rigorous validation and calibration when applied in diverse environments or under climate changes. Despite advances in data analysis techniques, empirical models remain limited by their dependency on data alone.

In contrast, **mechanistic models**, developed from a deep understanding of biological and epidemiological processes, explain disease dynamics based on known system behaviors in response to external variables---a concept-driven approach. These dynamic models quantitatively characterize the state of the pathosystem over time, offering generally more robust predictions by utilizing mathematical equations to describe how epidemics evolve under varying environmental conditions.

It is worth noting that the mathematical equations used to predict specific components of the mechanistic model are derived via empirical modeling using data from controlled environments. For example, an equation describing infection frequency is derived empirically from experiments where the models are fitted to the data.

This chapter focuses mainly on empirical modeling. We begin by examining the types of data utilized in model development, focusing on those collected under controlled conditions, such as replicated laboratory or growth chamber experiments, as well as field data collected from several locations and years. We will also analyze real-world case studies, drawing on examples from the literature to replicate and understand model applications. Through these examples, we aim to illustrate the process of fitting models to data and underscore the role of modeling in advancing plant disease management practices.
