---
title: "Theoretical basis"
editor: visual
bibliography: references.bib
---

::: {.callout-note appearance="simple"}
This is a work in progress that is currently undergoing heavy technical editing and copy-editing
:::

## Epidemics and yield

Plant disease epidemics can also be studied in regard to their potential to reduce crop yield (the measurable produce such as seed, fruit, leaves, roots or tubers) and quality (e.g. blemishes on fruit and toxins in grain) of the agricultural production. The yield of some crops that host the pathogen for long time may be reduced because its physiology is negatively affected in a dynamic way as the crop grows (biomass increase) and develops (advances the phenological stages). For some diseases that primarily infect the product (e.g. grains), yield may directly impacted by reducing size and weight of the affected plant part. There are cases of diseases causing visual damages on the product (e.g. fruit, tuber) that do no result in yield reduction, but the presence of the symptoms may reduce sales. Another example is the presence of toxins that downgrade product value.

Losses can be direct (on the farm) and indirect (on the society). Costs on farm that are due to reduction in quantity an quality of yield and control costs are classified as primary. Other consequences of the epidemics such as the build-up of inoculum in soil and the reduced efficacy of control due to surge of resistance to chemicals in the pathogen population over the years are examples of secondary losses on farm.

The famous epidemics in the ancient history, such as the late blight of potatoes, serve us as a remind of worst-case scenarios of major impact of epidemics causing both direct and indirect losses. However, crop losses due to diseases occur regularly and at levels that depend on the intensity of epidemics [@chapter2017a]. Expert opinion estimates have indicated that around 20% (on average) of the yield of major crops like wheat, rice, maize, potato and soybean is lost due to the pests and pathogens globally [@savary2019].

According to @chapter2017a, knowledge about the disease:yield relationship falls within crop loss assessment, a general branch of epidemiology that study the relationship between the attack by harmful organisms and the resulting yield (or yield loss) of crops. In fact, the study (analysis and modeling) of crop losses is considered central to plant pathology as no plant protection scientific reasoning could be possible without a measure of crop loss [@Savary2006].

The concept of yield levels is important to recognize as a framework to study crop loss: There are three levels (from higher to lower) of yield: theoretical, attainable and actual. The **theoretical** (also known as potential) yield is determined mainly by the genotype of the crop grown under ideal conditions. It can be obtained in experimental plots managed with high input of fertilizers and pesticides. The **attainable** yield is obtained in commercial crops managed with a full range of modern technology to maximize yield. It considers the presence of *limiting factors* such as water and fertilizers. The **actual** yield is generally less than or equal to attainable yield, and is obtained under the effect of *reducing factors* such as those caused by pest (disease, insects, weeds) injuries - defined as measurable symptom caused by a harmful organism. It is the crop yield actually harvested in a farmer's field.

**Yield loss** (expressed in absolute or relative terms) is the difference between the attainable and the actual yield. Yield loss studies are only possible when reliable field data are collected in sufficient number to allow the development of statistical models (that summarizes the relationship) as well as the validation of mechanistic simulation models. Whenever established, knowledge of the empirical disease:yield relationship and of the theoretical basis of damage on crops, can further be used for several purposes such as: 1) determine the effect of control on crop yield; 2) make prediction of yield in given location or region; and 3) determine the economic importance of diseases.
