{
  "hash": "6fd68421cd6c174227a751dedbee9cb9",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Disease modeling\"\neditor_options: \n  chunk_output_type: console\n---\n\n## Introduction\n\nAs seen in the previous chapter, plant disease modeling is a crucial tool for predicting disease dynamics and informing management decisions when integrated into decision support systems. By leveraging models, researchers and practitioners can anticipate disease outbreaks, assess potential risks, and implement timely interventions to mitigate losses [@savary2018; @rossi2010a].\n\nMathematical modeling involves representing empirical phenomena and experimental outcomes using mathematical functions. The data used for these models may be collected specifically for modeling purposes or drawn from existing experiments and observations originally conducted to address different research questions, with such data often found in the literature [@hau1990].\n\nMathematical models integrating plant, disease, and environmental - in most cases weather-based variables - factors have been developed since the mid-1900s (see the recent review by @gonzález-domínguez2023). Dynamic modeling of disease epidemics gained traction in the early 1960s with foundational work by Vanderplank and Zadoks, setting the stage for future advancements. Since then, researchers have contributed extensively to model development, mainly focusing on the plant disease cycle, which outlines pathogen development stages, such as dormancy, reproduction, dispersal, and pathogenesis, driven by interactions among host, pathogen, and environmental factors [@dewolf2007].\n\nA systematic map by @fedele2022a identified over 750 papers on plant disease models, primarily aimed at understanding system interactions (n = 680). This map revealed that while most models focus on system understanding, fewer are devoted to tactical management (n = 40), strategic planning (n = 38), or scenario analysis (n = 9).\n\nIn terms of model development, we can classify the models into two main groups based on the approach taken [@gonzález-domínguez2023]: Empirical or mechanistic approaches, which differ fundamentally in their basis, complexity and application (@fig-approaches_modeling).\n\n![Steps of model development from data collection to modeling based on statistical relationships (data-driven) between data collected from field or controlled environment to mechanistic approach based on the elements of the disease cycles (concept-driven).](imgs/modeling-fig1.png){#fig-approaches_modeling fig-align=\"center\" width=\"614\"}\n\n**Empirical models**, which emerged in the mid-20th century, rely on data-driven statistical relationships between variables collected under varying field or controlled environments. These models often lack cause-effect understanding, making them less robust and requiring rigorous validation and calibration when applied in diverse environments, especially in regions that did not provide data for model construction. The parameters of the model change every time new data are incorporated during model development.\n\nIn contrast, **mechanistic models**, developed from a deep understanding of biological and epidemiological processes, explain disease dynamics based on known system behaviors in response to external variables---a concept-driven approach. These dynamic models quantitatively characterize the state of the pathosystem over time, offering generally more robust predictions by utilizing mathematical equations to describe how epidemics evolve under varying environmental conditions.\n\nBoth empirical and mechanistic approaches are valid methodologies extensively used in plant pathology research. The choice between these approaches depends on several factors, including data availability, urgency in model development, and, frequently, the researcher's experience or preference. Empirical models focus on statistical relationships derived directly from data, whereas mechanistic models aim to represent the biological processes of disease progression through linked mathematical equations.\n\nIn mechanistic modeling, the equations used to predict specific disease components---such as infection frequency or the latency period---are often empirically derived from controlled experiments. For example, an infection frequency equation is typically based on data collected under specific environmental conditions, with models fitted to accurately describe observed patterns. These process-based models are then built by integrating empirically-derived equations or rules, which collectively simulate the disease cycle. Data and equations are sourced from published studies or generated from new experiments conducted by researchers.\n\nBeyond their practical predictive value, mechanistic models are valuable tools for organizing existing knowledge about a particular disease, helping to identify gaps and guide future research efforts. An example of such work is the extensive collection of comprehensive mechanistic models developed for various plant diseases by the research group led by Prof. Vittorio Rossi in Italy [@rossi2008; @rossi2014; @salotti2023; @salotti2022].\n\nThis chapter focuses mainly on empirical modeling. We begin by examining the types of data utilized in model development, focusing on those collected under controlled conditions, such as replicated laboratory or growth chamber experiments, as well as field data collected from several locations and years. We will also analyze real-world case studies, drawing on examples from the literature to replicate and understand model applications. Through these examples, we aim to illustrate the process of fitting models to data and underscore the role of modeling in advancing plant disease management practices.\n\n## Controlled environment\n\nIn this section, we will demonstrate, using examples from the literature, how statistical models can be fitted to data that represent various stages of the disease cycle.\n\nResearch on disease-environment interactions under controlled conditions - such as laboratory or growth chamber studies - lays the groundwork for building foundational models, including infection-based models and sub-models for specific processes like dormancy, dispersal, infection, and latency [@krause1975; @magarey2005; @dewolf2007].\n\nGrowth chambers and phytotrons are essential for testing the effects of individual variables, though these controlled results may not fully replicate field conditions. Laboratory experiments help clarify specific questions by isolating interactions, unlike complex field trials where host, pathogen, and environment factors interact. Polycyclic or \"mini epidemic\" experiments enable observation of disease dynamics under targeted conditions [@hau1990; @rotem1988].\n\nOnce developed, these sub-models can be incorporated into larger mechanistic models that simulate the entire disease cycle, thereby mimicking disease progression over time [@rossi2008; @salotti2023]. Alternatively, sub-models can also be used in stand-alone predictive systems where the process being modeled - such as infection - is the key factor in determining disease occurrence [@machardy1989; @magarey2007]. For example, infection sub-models can be integrated into prediction systems that help schedule crop protection measures by forecasting when infection risk is highest.\n\n### Infection-based models\n\nTo model infection potential based on environmental factors, simple rules can be used with daily weather data, such as temperature and rainfall thresholds [@magarey2002]. Simple decision aids, such as charts and graphs, also exist to help model infection potential by using combinations of daily average temperature and hours of wetness. These tools offer a straightforward approach to evaluate infection risks based on readily available weather data, supporting decision-making without complex modeling [@seem1984]. However, for many pathogens, hourly data is needed, requiring complex models that track favorable conditions hour by hour. These models start with specific triggers and can reset due to conditions like dryness or low humidity, simulating a biological clock for infection risk assessment [@magarey2007].\n\nModeling approaches vary based on available data and model goals. A common method is the matrix approach, like the Wallin potato late blight model, which uses rows for temperature and columns for moisture duration to estimate disease severity [@krause1975] (see previous chapter on [warning systems](prediction-warning-systems.qmd)). Bailey enhanced this with an interactive matrix that combines temperature, relative humidity, and duration to assess infection risk across pathogens, making it versatile for various modeling needs [@bailey1999].\n\nWhen infection responses are measured at various temperature and wetness combinations, regression models can be developed to predict infection rates. These models often use polynomial, logistic, or complex three-dimensional response surface equations to represent the relationship between environmental conditions and infection potential. In an excellent review titled \"*How to create and deploy infection models for plant pathogens*\", @magarey2007 discusses that many modeling approaches lack biological foundations and are not generic, making them unsuitable for developing a unified set of disease forecast models. While three-dimensional response surfaces, such as those created with sufficient temperature-moisture observations, offer detailed infection responses, they are often too complex and data-intensive for widespread use (see Table 1 adapted from @magarey2007).\n\n| Approach | Strengths | Weaknesses |\n|----|----|----|\n| Matrix [@krause1975; @mills1944; @windels1998] | Easy; converts moisture/temperature combinations into severity values or risk categories. Tried and true approach. | Data to populate matrix may not be readily available. |\n| Regression:<br>• Polynomial [@evans1992]<br>• Logistic [@bulger1987] | Widely used in plant pathology. Available for many economically important pathogens. | Parameters not biologically based. Requires dataset for development. |\n| Three-dimensional response surface [@duthie1997] | Describes infection response in detail. | Parameters not biologically based. Complex, requires extensive data and processing time. |\n| Degree wet hours [@pfender2003] | Simple; based on degree hours, commonly used in entomology. Requires only Tmin and Tmax | Recently developed; assumes linear thermal response. |\n| Temperature-moisture response function [@magarey2005] | Simple; based on crop modeling functions, requires only Tmin, Topt and Tmax | Recently developed. |\n\n: Comparison of different infection modeling approaches. Source: @magarey2007\n\nIn the following sections, we demonstrate how various biologically meaningful models fit infection data, using temperature, wetness duration, or a combination of both as predictors.\n\n#### Temperature effects\n\n##### Generalized beta-function\n\nAmong several non-linear models that can be fitted to infection responses to temperature, the generalized beta-function is an interesting alternative [@hau1990]. This is a nonlinear model with five parameters. Two of them, namely $b$ and $c$ , have a biological meaning because they are estimates of the minimum and maximum temperature of the biological process under consideration.\n\nWe will use a subset of the data obtained from a study conducted under controlled conditions that aimed to assess the influence of temperature on the symptom development of citrus canker in sweet orange [@dallapria2006]. The data used here is only for severity on the cultivar Hamlin (plot a in @fig-temperature). The data was extracted using the R package {digitize} as shown [here on this tweet](https://twitter.com/edelponte/status/1580320409794539520?s=20&t=KqjJPmwzFVKm8Gu7Ss-P6A).\n\n![Effect of temperature (12, 15, 20, 25, 30, 35 or 40°C) on disease severity of citrus canker on sweet orange cvs Hamlin (a), Natal (b), Pera (c) and Valencia (d) with a leaf wetness duration of 24 h. Each point represents the mean of three repetitions. Vertical bars represent standard errors. Lines show the generalized beta function fitted to data. Source: @dallapria2006](imgs/modeling-fig_temperature.gif){#fig-temperature fig-align=\"center\" width=\"441\"}\n\nLet's enter the data manually. Where $t$ is the temperature and $y$ is the severity on leaves.\n\n::: {.cell}\n\n```{.r .cell-code}\ntemp <- tibble::tribble(\n  ~t, ~y,\n12.0, 0.00,\n15.0, 0.1,\n20.0, 0.5,\n25.0, 1.2,\n30.0, 1.5,\n35.0, 1.2,\n40.0, 0.1\n)\n```\n:::\n\nFit the generalized beta-function [@hau1990]. The model can be written as:\n\n$$\ny = a*((t - b )^d)*((c - t)^e)\n$$\n\nwhere $b$ and $c$ represent minimum and maximum temperatures, respectively, for the development of the disease, $a$, $d$ and $e$ are parameters to be estimated, $t$ is the temperature and $y$ is disease severity. We need the {minpack.lm} library to avoid parameterization issues.\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(minpack.lm)\nfit_temp <- nlsLM(\n  y ~ a * ((t - b) ^ d) * ((c - t) ^ e),\n  start = list(\n    a = 0,\n    b = 10,\n    c = 40,\n    d = 1.5,\n    e = 1\n  ),\n  algorithm = \"port\",\n  data = temp\n)\nsummary(fit_temp)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nFormula: y ~ a * ((t - b)^d) * ((c - t)^e)\n\nParameters:\n   Estimate Std. Error t value Pr(>|t|)    \na  0.001303   0.006295   0.207    0.855    \nb 11.999999   4.875414   2.461    0.133    \nc 40.137236   0.346763 115.748 7.46e-05 ***\nd  1.760101   1.193017   1.475    0.278    \ne  0.830868   0.445213   1.866    0.203    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.1121 on 2 degrees of freedom\n\nAlgorithm \"port\", convergence message: Relative error between `par' and the solution is at most `ptol'.\n```\n\n\n:::\n\n```{.r .cell-code}\nmodelr::rsquare(fit_temp, temp)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.9898275\n```\n\n\n:::\n:::\n\nStore the model parameters in objects.\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_temp$m$getAllPars()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          a           b           c           d           e \n 0.00130259 11.99999931 40.13723602  1.76010097  0.83086798 \n```\n\n\n:::\n\n```{.r .cell-code}\na <- fit_temp$m$getAllPars()[1]\nb <- fit_temp$m$getAllPars()[2]\nc <- fit_temp$m$getAllPars()[3]\nd <- fit_temp$m$getAllPars()[4]\ne <- fit_temp$m$getAllPars()[5]\n```\n:::\n\nCreate a data frame for predictions at each temperature unit from 10 to 45 degree Celsius.\n\n::: {.cell}\n\n```{.r .cell-code}\nt <- seq(10, 45, 0.1)\ny <- a * ((t - b) ^ d) * ((c - t) ^ e)\ndat <- data.frame(t, y)\n```\n:::\n\nPlot the observed and predicted data using {ggplot2} package.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\nlibrary(r4pde)\ndat |>\n  ggplot(aes(t, y)) +\n  geom_line() +\n  geom_point(data = temp, aes(t, y)) +\n  theme_r4pde(font_size = 16) +\n  labs(x = \"Temperature\", y = \"Severity\",\n       title = \"Generalized beta-function\")\n```\n\n::: {.cell-output-display}\n![Generalized beta function fitted to the severity of citrus canker as a function of temperature (points are the observed values)](prediction-disease-modeling_files/figure-html/fig-genbeta-fit-1.png){#fig-genbeta-fit width=672}\n:::\n:::\n\n\n##### Analytis beta function\n\n@ji2023a tested and compared various mathematical equations to describe the response of mycelial growth to temperature for several fungi associated with Grapevine trunk diseases. The authors found that the beta equation [@analytis1977] provided the best fit and, therefore, was considered the most suitable for all fungi.\n\nThe model equation for re-scaled severity (0 to 1) as a function of temperature is given by:\n\n$Y = \\left( a \\cdot T_{eq}^b \\cdot (1 - T_{eq}) \\right)^c \\quad ; \\quad \\text{if } Y > 1, \\text{ then } Y = 1$\n\nwhere\n\n$T_{eq} = \\frac{T - T_{\\text{min}}}{T_{\\text{max}} - T_{\\text{min}}}$\n\n$T$ is the temperature in degrees Celsius. $T_{\\text{min}}$ is the minimum temperature, $T_{\\text{max}}$ is the maximum temperature for severity. The $a$ , $b$ , and $c$ are parameters that define the top, symmetry, and size of the unimodal curve.\n\nLet's rescale (0 to 1) the data on the citrus canker using the function rescale of the {scales} package.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(scales)\ntemp$yscaled <- rescale(temp$y)\ntemp\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 7 × 3\n      t     y yscaled\n  <dbl> <dbl>   <dbl>\n1    12   0    0     \n2    15   0.1  0.0667\n3    20   0.5  0.333 \n4    25   1.2  0.8   \n5    30   1.5  1     \n6    35   1.2  0.8   \n7    40   0.1  0.0667\n```\n\n\n:::\n:::\n\n\nNow we can fit the model using the same `nlsLM` function.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Define the minimum and maximum temperatures\nTmin <- 12\nTmax <- 40\n\nlibrary(minpack.lm)\nfit_temp2 <- nlsLM(\n  yscaled ~ (a * ((t - Tmin) / (Tmax - Tmin))^b * (1 - ((t - Tmin) / (Tmax - Tmin))))^c,\n  data = temp,\n  start = list(a = 1, b = 2, c = 3), # Initial guesses for parameters\n  algorithm = \"port\" \n)\n\nsummary(fit_temp2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nFormula: yscaled ~ (a * ((t - Tmin)/(Tmax - Tmin))^b * (1 - ((t - Tmin)/(Tmax - \n    Tmin))))^c\n\nParameters:\n  Estimate Std. Error t value Pr(>|t|)    \na   6.7625     0.3218  21.013 3.03e-05 ***\nb   1.9648     0.1030  19.072 4.45e-05 ***\nc   1.1607     0.1507   7.701  0.00153 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.03955 on 4 degrees of freedom\n\nAlgorithm \"port\", convergence message: Relative error in the sum of squares is at most `ftol'.\n```\n\n\n:::\n\n```{.r .cell-code}\nmodelr::rsquare(fit_temp2, temp)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.9948325\n```\n\n\n:::\n:::\n\n\nLet's store the model parameters in objects.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_temp2$m$getAllPars()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       a        b        c \n6.762509 1.964817 1.160702 \n```\n\n\n:::\n\n```{.r .cell-code}\na <- fit_temp2$m$getAllPars()[1]\nb <- fit_temp2$m$getAllPars()[2]\nc <- fit_temp2$m$getAllPars()[3]\n```\n:::\n\n\nAgain, we create a data frame for predictions at each temperature unit from 10 to 45 degree Celsius.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nTmin <- 12\nTmax <- 40\nt <- seq(10, 45, 0.1)\ny <- (a * ((t - Tmin) / (Tmax - Tmin))^b * (1 - ((t - Tmin) / (Tmax - Tmin))))^c\ndat2 <- data.frame(t, y)\n```\n:::\n\n\nAnd now we can plot the observed and predicted data using {ggplot2} package.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\nlibrary(r4pde)\ndat2 |>\n  ggplot(aes(t, y)) +\n  geom_line() +\n  geom_point(data = temp, aes(t, yscaled)) +\n  theme_r4pde(font_size = 16) +\n  labs(x = \"Temperature\", y = \"Scaled severity\", \n       title = \"Analytis beta function\")\n```\n\n::: {.cell-output-display}\n![Analytis beta function fitted to the rescaled severity of citrus canker as a function of temperature](prediction-disease-modeling_files/figure-html/fig-analytis-fit-1.png){#fig-analytis-fit width=672}\n:::\n:::\n\n\n#### Moisture effects\n\n##### Monomolecular function\n\nFor this example, we will use a subset of the data obtained from a study conducted under controlled conditions that aimed to assess the effects of moisture duration on the symptom development of citrus canker in sweet orange [@dallapria2006]. As in the previous example for temperature effects, the data used here is only for severity on the cultivar Hamlin (plot a in @fig-moisture). The data was also extracted using the R package digitize.\n\nLet's look at the original data and the predictions by the model fitted in the paper.\n\n![Effect of leaf wetness duration (0, 4, 8, 12, 16, 20 or 24 h) on disease severity of citrus canker on sweet orange cvs Hamlin (a), Natal (b), Pera (c) and Valencia (d) at 30°C. Each point represents the mean of three repetitions. Vertical bars represent standard errors. Lines show the monomolecular model fitted to data. Source: @dallapria2006](imgs/modeling-fig2.gif){#fig-moisture fig-align=\"center\" width=\"516\"}\n\nFor this pattern in the data, we will fit a three-parameter asymptotic regression model. These models describe a limited growth, where y approaches a horizontal asymptote as x tends to infinity. This equation is also known as Monomolecular Growth, Mitscherlich law or von Bertalanffy law. See [this tutorial](https://www.statforbiology.com/nonlinearregression/usefulequations) for comprehensive information about fitting several non-linear regression models in R.\n\nAgain, we enter the data manually. Here $x$ is wetness duration in hours and $y$ is severity.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwet <- tibble::tribble(~ x, ~ y,\n                       0 ,  0,\n                       4 ,  0.50,\n                       8 ,  0.81,\n                       12,  1.50,\n                       16,  1.26,\n                       20,  2.10,\n                       24,  1.45)\n```\n:::\n\n\nThe model can be written as:\n\n$y = c1 + (d1-c1)*(1-exp(-x/e1))$\n\nwhere $c$ is the lower limit (at $x = 0$), the parameter $d$ is the upper limit and the parameter $e$ (greater than 0) is determining the steepness of the increase as $x$.\n\nWe will solve the model again using the `nlsLM` function. We should provide initial values for the three parameters.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_wet <- nlsLM(y ~ c1 + (d1 - c1) * (1 - exp(-x / e1)),\n                 start = list(c1 = 0.5,\n                              d1 = 3,\n                              e1 = 1),\n                 data = wet)\n\nsummary(fit_wet)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nFormula: y ~ c1 + (d1 - c1) * (1 - exp(-x/e1))\n\nParameters:\n   Estimate Std. Error t value Pr(>|t|)  \nc1 -0.04898    0.31182  -0.157   0.8828  \nd1  2.00746    0.70594   2.844   0.0467 *\ne1 11.63694    9.33183   1.247   0.2804  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.3296 on 4 degrees of freedom\n\nNumber of iterations to convergence: 7 \nAchieved convergence tolerance: 1.49e-08\n```\n\n\n:::\n\n```{.r .cell-code}\nmodelr::rsquare(fit_wet, wet)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.8532282\n```\n\n\n:::\n:::\n\n\nStore the value of the parameters in the respective object.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nHW <- seq(0, 24, 0.1)\nc1 <-  fit_wet$m$getAllPars()[1]\nd1 <- fit_wet$m$getAllPars()[2]\ne1 <- fit_wet$m$getAllPars()[3]\ny <-  (c1 + (d1 - c1) * (1 - exp(-HW / e1)))\ndat2 <- data.frame(HW, y)\n```\n:::\n\n\nNow we can plot the predictions and the original data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat2 |>\n  ggplot(aes(HW, y)) +\n  geom_line() +\n  geom_point(data = wet, aes(x, y)) +\n  theme_r4pde(font_size = 16) +\n  labs(x = \"Wetness duration\", y = \"Severity\")\n```\n\n::: {.cell-output-display}\n![Monomolecular model fitted to the severity of citrus canker as a function of leaf wetness duration](prediction-disease-modeling_files/figure-html/fig-mono-wet-fit-1.png){#fig-mono-wet-fit width=672}\n:::\n:::\n\n\n##### Weibull function\n\nIn the studies by @ji2021 and @ji2023a, a Weibull model was fitted to the re-scaled data (0 to 1) on the effect of moisture duration on spore germination or infection. Let's keep working with the re-scaled data on the citrus canker.\n\nThe model is given by:\n\n$y = 1 - \\exp(-(a \\cdot x)^b)$\n\nwhere $y$ is the response variable, $x$ is the moisture duration, $a$ is the scale parameter influencing the rate of infection and $b$ is the shape parameter affecting the curve's shape and acceleration\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwet$yscaled <- rescale(wet$y) \nwet\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 7 × 3\n      x     y yscaled\n  <dbl> <dbl>   <dbl>\n1     0  0      0    \n2     4  0.5    0.238\n3     8  0.81   0.386\n4    12  1.5    0.714\n5    16  1.26   0.6  \n6    20  2.1    1    \n7    24  1.45   0.690\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_wet2 <- nlsLM(\n  yscaled ~ 1 - exp(-(a * x)^b),\n  data = wet,\n  start = list(a = 1, b = 2),  # Initial guesses for parameters a and b\n  )\nsummary(fit_wet2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nFormula: yscaled ~ 1 - exp(-(a * x)^b)\n\nParameters:\n  Estimate Std. Error t value Pr(>|t|)   \na  0.07684    0.01296    5.93  0.00195 **\nb  1.07610    0.37103    2.90  0.03378 * \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.1404 on 5 degrees of freedom\n\nNumber of iterations to convergence: 26 \nAchieved convergence tolerance: 1.49e-08\n```\n\n\n:::\n\n```{.r .cell-code}\nmodelr::rsquare(fit_wet2, wet)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.8534077\n```\n\n\n:::\n:::\n\n\nSet the value of the parameters in the respective objects\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx <- seq(0, 24, 0.1)\na <-  fit_wet2$m$getAllPars()[1]\nb <- fit_wet2$m$getAllPars()[2]\ny <-  1 - exp(-(a * x)^b)\ndat3 <- data.frame(x, y)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat3 |>\n  ggplot(aes(x, y)) +\n  geom_line() +\n  geom_point(data = wet, aes(x, yscaled)) +\n  theme_r4pde(font_size = 16) +\n  labs(x = \"Wetness duration\", y = \"Scaled severity\")\n```\n\n::: {.cell-output-display}\n![Weibull model fitted to the rescaled severity of citrus canker as a function of wetness duration](prediction-disease-modeling_files/figure-html/fig-weibull-wet-fit-1.png){#fig-weibull-wet-fit width=672}\n:::\n:::\n\n\n#### Integrating temperature and wetness effects\n\nThe equations developed for the separate effects can be integrated to create a surface response curve or a simple contour plot. Let's first integrate the generalized beta and the monomolecular models for the original severity data for the citrus canker experiment.\n\nFirst, we need a data frame for the interaction between temperature $t$ and hours of wetness $hw$. Then, we obtain the disease value for each combination of $t$ and $hw$.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt <- rep(1:40, 40)\nhw <- rep(1:40, each = 40)\n\n# let's fit the two models again and store the parameters in objects\n# Temperature effects\nfit_temp <- nlsLM(\n  y ~ a * ((t - b) ^ d) * ((c - t) ^ e),\n  start = list(\n    a = 0,\n    b = 10,\n    c = 40,\n    d = 1.5,\n    e = 1\n  ),\n  algorithm = \"port\",\n  data = temp\n)\nfit_temp$m$getAllPars()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          a           b           c           d           e \n 0.00130259 11.99999931 40.13723602  1.76010097  0.83086798 \n```\n\n\n:::\n\n```{.r .cell-code}\na <- fit_temp$m$getAllPars()[1]\nb <- fit_temp$m$getAllPars()[2]\nc <- fit_temp$m$getAllPars()[3]\nd <- fit_temp$m$getAllPars()[4]\ne <- fit_temp$m$getAllPars()[5]\n\n## Moist duration effects\nfit_wet <- nlsLM(y ~ c1 + (d1 - c1) * (1 - exp(-x / e1)),\n                 start = list(c1 = 0.5,\n                              d1 = 3,\n                              e1 = 1),\n                 data = wet)\n\nc1 <-  fit_wet$m$getAllPars()[1]\nd1 <- fit_wet$m$getAllPars()[2]\ne1 <- fit_wet$m$getAllPars()[3]\n\ndis <-\n  (a * (t - b) ^ d) * ((c - t) ^ e) * (c1 + (d1 - c1) * (1 - exp(- hw / e1)))\nvalidation <- data.frame(t, hw, dis)\n```\n:::\n\n\nNow the contour plot can be visualized using {ggplot2} and {geomtextpath} packages.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(geomtextpath)\nggplot(validation, aes(t, hw, z = dis)) +\n  geom_contour_filled(bins = 8, alpha = 0.7) +\n  geom_textcontour(bins = 8,\n                   size = 2.5,\n                   padding = unit(0.05, \"in\")) +\n  theme_light(base_size = 10) +\n  theme(legend.position = \"right\") +\n  ylim(0, 40) +\n  labs(y = \"Wetness duration (hours)\",\n       fill = \"Severity\",\n       x = \"Temperature (Celsius)\",\n       title = \"Integrating generalized beta and monomolecular\")\n```\n\n::: {.cell-output-display}\n![Predicted severity of citrus canker as a function of temperature and wetness duration, integrating the generalized beta and monomolecular models](prediction-disease-modeling_files/figure-html/fig-contour-genbeta-1.png){#fig-contour-genbeta width=672}\n:::\n:::\n\n\nIn the second example, let's integrate the Analytis beta and the Weibull model:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_temp2 <- nlsLM(\n  yscaled ~ (a * ((t - Tmin) / (Tmax - Tmin))^b * (1 - ((t - Tmin) / (Tmax - Tmin))))^c,\n  data = temp,\n  start = list(a = 1, b = 2, c = 3), # Initial guesses for parameters\n  algorithm = \"port\" \n)\n\nfit_temp2$m$getAllPars()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       a        b        c \n6.762509 1.964817 1.160702 \n```\n\n\n:::\n\n```{.r .cell-code}\na2 <- fit_temp2$m$getAllPars()[1]\nb2 <- fit_temp2$m$getAllPars()[2]\nc2 <- fit_temp2$m$getAllPars()[3]\n\n\nfit_wet2 <- nlsLM(\n  yscaled ~ 1 - exp(-(d * x)^e),\n  data = wet,\n  start = list(d = 1, e = 2),  # Initial guesses for parameters a and b\n  )\n\nd2 <-  fit_wet2$m$getAllPars()[1]\ne2 <- fit_wet2$m$getAllPars()[2]\n\nTmin <- 12\nTmax <- 40\ndis2 <-  (a2 * ((t - Tmin) / (Tmax - Tmin))^b2 * (1 - ((t - Tmin) / (Tmax - Tmin))))^c2 * (1 - exp(-(d2 * hw)^e2))\n\nt <- rep(1:40, 40)\nhw <- rep(1:40, each = 40)\nvalidation2 <- data.frame(t, hw, dis2)\n\nvalidation2 <- validation2 |> \n  filter(!is.nan(dis2)) |> \n  mutate(dis2 = case_when(dis2 < 0 ~ 0,\n                          TRUE ~ dis2))\n```\n:::\n\n\nNow the plot.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(validation2, aes(t, hw, z = dis2)) +\n  geom_contour_filled(bins = 7, alpha = 0.7) +\n  geom_textcontour(bins = 7,\n                   size = 2.5,\n                   padding = unit(0.05, \"in\")) +\n  theme_light(base_size = 10) +\n  theme(legend.position = \"right\") +\n  ylim(0, 40) +\n  labs(y = \"Wetness duration (hours)\",\n       fill = \"Severity\",\n       x = \"Temperature (Celsius)\",\n       title = \"Integrating Analytis beta and Weibull\")\n```\n\n::: {.cell-output-display}\n![Predicted severity as a function of temperature and wetness duration, integrating the Analytis beta and Weibull models](prediction-disease-modeling_files/figure-html/fig-contour-analytis-1.png){#fig-contour-analytis width=672}\n:::\n:::\n\n\nWe can create a 3D surface plot to visualize the predictions, as [it was used in the original paper](https://bsppjournals.onlinelibrary.wiley.com/cms/asset/0acf45ce-bad8-4a49-9a17-181836aa9876/ppa_1393_f3.gif). Note that In `plot_ly`, a 3D surface plot requires a matrix or grid format for the `z` values, with corresponding vectors for `x` and `y` values that define the axes. If the data frame (`validation2`) has three columns (`t`, `hw`, and `dis2`), we'll need to convert `dis2` into a matrix format that `plot_ly` can interpret for a surface plot.\n\n::: {.content-visible when-format=\"html\"}\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(plotly)\nlibrary(reshape2)  \nz_matrix <- acast(validation2, hw ~ t, value.var = \"dis2\")\nx_vals <- sort(unique(validation2$t))  \ny_vals <- sort(unique(validation2$hw)) \n\nplot_ly(x = ~x_vals, y = ~y_vals, z = ~z_matrix, type = \"surface\") |> \n    config(displayModeBar = FALSE) |> \n  layout(\n    scene = list(\n      xaxis = list(title = \"Temperature (°C)\", nticks = 10),\n      yaxis = list(title = \"Wetness Duration (hours)\", range = c(0, 40)),\n      zaxis = list(title = \"Severity\"),\n      aspectratio = list(x = 1, y = 1, z = 1)  \n    ),\n    title = \"Integrating Analytis Beta and Weibull\"\n  )\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"plotly html-widget html-fill-item\" id=\"htmlwidget-5a52dcd41862cf9a7d96\" style=\"width:100%;height:464px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-5a52dcd41862cf9a7d96\">{\"x\":{\"visdat\":{\"23dc1e9f63f4\":[\"function () \",\"plotlyVisDat\"]},\"cur_data\":\"23dc1e9f63f4\",\"attrs\":{\"23dc1e9f63f4\":{\"x\":{},\"y\":{},\"z\":{},\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"type\":\"surface\"}},\"layout\":{\"margin\":{\"b\":40,\"l\":60,\"t\":25,\"r\":10},\"scene\":{\"xaxis\":{\"title\":\"Temperature (°C)\",\"nticks\":10},\"yaxis\":{\"title\":\"Wetness Duration (hours)\",\"range\":[0,40]},\"zaxis\":{\"title\":\"Severity\"},\"aspectratio\":{\"x\":1,\"y\":1,\"z\":1}},\"title\":\"Integrating Analytis Beta and Weibull\",\"hovermode\":\"closest\",\"showlegend\":false,\"legend\":{\"yanchor\":\"top\",\"y\":0.5}},\"source\":\"A\",\"config\":{\"modeBarButtonsToAdd\":[\"hoverclosest\",\"hovercompare\"],\"showSendToCloud\":false,\"displayModeBar\":false},\"data\":[{\"colorbar\":{\"title\":\"z_matrix\",\"ticklen\":2,\"len\":0.5,\"lenmode\":\"fraction\",\"y\":1,\"yanchor\":\"top\"},\"colorscale\":[[\"0\",\"rgba(68,1,84,1)\"],[\"0.0416666666666667\",\"rgba(70,19,97,1)\"],[\"0.0833333333333333\",\"rgba(72,32,111,1)\"],[\"0.125\",\"rgba(71,45,122,1)\"],[\"0.166666666666667\",\"rgba(68,58,128,1)\"],[\"0.208333333333333\",\"rgba(64,70,135,1)\"],[\"0.25\",\"rgba(60,82,138,1)\"],[\"0.291666666666667\",\"rgba(56,93,140,1)\"],[\"0.333333333333333\",\"rgba(49,104,142,1)\"],[\"0.375\",\"rgba(46,114,142,1)\"],[\"0.416666666666667\",\"rgba(42,123,142,1)\"],[\"0.458333333333333\",\"rgba(38,133,141,1)\"],[\"0.5\",\"rgba(37,144,140,1)\"],[\"0.541666666666667\",\"rgba(33,154,138,1)\"],[\"0.583333333333333\",\"rgba(39,164,133,1)\"],[\"0.625\",\"rgba(47,174,127,1)\"],[\"0.666666666666667\",\"rgba(53,183,121,1)\"],[\"0.708333333333333\",\"rgba(79,191,110,1)\"],[\"0.75\",\"rgba(98,199,98,1)\"],[\"0.791666666666667\",\"rgba(119,207,85,1)\"],[\"0.833333333333333\",\"rgba(147,214,70,1)\"],[\"0.875\",\"rgba(172,220,52,1)\"],[\"0.916666666666667\",\"rgba(199,225,42,1)\"],[\"0.958333333333333\",\"rgba(226,228,40,1)\"],[\"1\",\"rgba(253,231,37,1)\"]],\"showscale\":true,\"x\":[12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40],\"y\":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40],\"z\":[[0,0.00027038475657750071,0.0012574098554115215,0.0030289641186321123,0.0055673364081423498,0.0088146183038711121,0.01268744324497605,0.0170844357477088,0.02189075289369561,0.026981196109761494,0.032222532383194266,0.037475348519690581,0.042595623292865398,0.04743613531904585,0.051847791091887273,0.055680942436520865,0.058786759463405287,0.061018732273268157,0.062234393872048412,0.062297393652018841,0.06108011787568654,0.058467177627335054,0.054360325873132775,0.048685870941320722,0.04140682883559358,0.032545204730372541,0.022230194185843218,0.010837189652127287,0],[0,0.00055075199947108016,0.0025612427297617983,0.0061697562605924254,0.011340216428338726,0.017954668439453599,0.025843301315484974,0.034799621350654147,0.04458970275816735,0.054958526115406754,0.065634706492705461,0.076334270427627485,0.086763858267055349,0.096623591894896013,0.10560977983176703,0.11341760078311973,0.11974390023579479,0.12429024931019135,0.12676645419941382,0.12689477968352819,0.12441528684447621,0.11909293774279689,0.1107276110735403,0.099169202829071698,0.08434237958389991,0.066291964108230558,0.045281117365705545,0.022074483580754724,0],[0,0.00082236602009969973,0.0038243692119253052,0.0092124911137522313,0.016932863902806124,0.026809361093456125,0.038588426132747405,0.051961728942604993,0.066579978701626435,0.082062388217340826,0.098003733823307473,0.11397999504144971,0.12955313622119569,0.14427538854267141,0.15769328918871453,0.16935168833675454,0.17879792495115013,0.18558639416757788,0.18928378748009772,0.18947539916330514,0.18577309638478573,0.17782592769083155,0.16533507807714504,0.14807641683611522,0.12593745840371121,0.098985130767810015,0.067612377820623792,0.032960942902604311,0],[0,0.0010812494757836413,0.0050282928824029157,0.01211261280737065,0.022263383664861552,0.035249033787752397,0.050736186208533408,0.068319447553525953,0.087539569132600956,0.10789589072612245,0.12885562296025296,0.14986126235304373,0.17033687822888396,0.18969374271000666,0.20733564143278246,0.2226641419534709,0.23508408409335307,0.24400958515034718,0.24887092971373678,0.24912286136820483,0.24425506182320283,0.23380609898393043,0.21738308992617111,0.19469134687807124,0.16558297345995437,0.13014596680453097,0.088896970799172817,0.04333715324285254,0],[0,0.0013259591823972978,0.0061663022905726304,0.014853954183992603,0.027302059943439195,0.043226638318255572,0.062218862057035217,0.083781588660890347,0.10735163171325483,0.13231502095994083,0.15801838548300037,0.18377804692913516,0.20888772928632965,0.23262546306193482,0.25426009792678317,0.27305776347298649,0.28828860214070878,0.29923413353663453,0.3051957035600113,0.30550465269530347,0.29953516679096409,0.28672138187493446,0.26658149727804481,0.23875413113072583,0.20305791496338069,0.15960076152765024,0.10901624218873079,0.053145270881793806,0],[0,0.001556067463573628,0.0072364085503535472,0.017431724232517636,0.032040086701396756,0.050728232316391411,0.073016385536458367,0.0983211292567963,0.12598154112747226,0.15527710188301655,0.18544105396364821,0.21567107279162748,0.24513831451022802,0.27299551831978269,0.29838464933256453,0.32044448053694746,0.33831849416301735,0.35116352401222456,0.35815967085320094,0.35852223533007888,0.35151679887824949,0.3364792969266322,0.31284431663659978,0.2801877615679092,0.23829678838555862,0.18729803712791593,0.12793502976784571,0.06236815428394351,0],[0,0.0017716540220343827,0.0082389823149921788,0.019846815816461416,0.036479105051459113,0.057756414113067728,0.083132496590472352,0.11194310540927484,0.14343575022640101,0.17679008688293429,0.21113312680574986,0.24555138674402177,0.27910119003412043,0.31081789148001104,0.33972457909331744,0.36484070650651385,0.38519108903928612,0.39981574338636472,0.4077811767494488,0.4081939729994471,0.40021796298925999,0.38309707881323007,0.35618757207797919,0.319006589577155,0.27131179943290096,0.21324738712468838,0.14565988644654138,0.071008997984091063,0],[0,0.0019730785082170861,0.0091756961196209439,0.022103257891761777,0.040626520348130628,0.064322908412627042,0.09258407133506788,0.12467024186386744,0.15974337684551226,0.19688986481344686,0.23513746459070956,0.27346883636523511,0.31083301413544756,0.34615567939407677,0.37834885219429804,0.40632050500702654,0.42898458157616504,0.44527195530909602,0.45414300190276979,0.45460273015615021,0.44571990442567633,0.42665249725178117,0.39668357061842069,0.35527537433722367,0.30215802511601925,0.23749210129979093,0.16222038156580579,0.079082216996045854,0],[0,0.0021608611732967182,0.010048969364515914,0.024206878531575046,0.044493044782973085,0.070444675548142988,0.10139552186114546,0.13653541102759925,0.17494654129535273,0.21562835057965526,0.25751606715367104,0.29949552850902267,0.34041574566184424,0.3791001546079939,0.41435722971145267,0.44499101253572476,0.46981208421782877,0.48764956679538024,0.49736489239998444,0.49786837410578588,0.48814014831537539,0.46725804977448138,0.43443690773795701,0.38908779302830376,0.33091513690614055,0.26009480034684268,0.17765928856002774,0.086608663311323136,0],[0,0.002335613720822834,0.010861646744331981,0.026164530297141345,0.048091273590590448,0.076141657225548637,0.10959555154002666,0.14757726378494065,0.18909476800702205,0.23306658495042709,0.27834183297339449,0.3237162453354458,0.36794575060040813,0.40975863401609908,0.4478670092256396,0.48097819858350038,0.50780659288418728,0.52708662325721978,0.53758764389879854,0.53813184303328487,0.52761687894575837,0.50504600929693377,0.46957056523745772,0.42055398987762521,0.3576768113273972,0.28112911274071256,0.19202689979355103,0.093612854389639621,0],[0,0.002497996560654346,0.011616799459811814,0.027983611378327423,0.051434804889080636,0.081435382990015501,0.11721514922148775,0.15783752856002525,0.20224152474702081,0.24927046900739758,0.29769346500020283,0.34622251970287204,0.39352706798767811,0.43824697951767205,0.47900482802526717,0.51441806284132729,0.54311169316791419,0.56373216184035346,0.5749632627763348,0.57554529719158853,0.5642992833957835,0.54015918083897962,0.50221731722591745,0.44979287924103539,0.38254418380744964,0.30067452955307289,0.20537751211206945,0.10012125986996372,0],[0,0.0026486912355177727,0.012317596988969103,0.029671756704298932,0.054537671931216773,0.086348071324079664,0.12428629538686643,0.1673592690708966,0.21444199023030899,0.26430801264207893,0.31565218464928885,0.36710881348678093,0.41726706607031222,0.46468476054928198,0.5079013757444405,0.5454509569392445,0.57587556534675544,0.59773998882324408,0.60964861955672944,0.61026576590462045,0.59834132267493967,0.57274493912749491,0.53251418653398297,0.47692718068913553,0.40562162606968316,0.31881308554005361,0.21776715983995928,0.1061611964097757,0],[0,0.0027883821578096328,0.012967222155064455,0.031236633351475571,0.057413967057490072,0.090902034262317757,0.13084110517292896,0.17618573035755353,0.22575157550460698,0.27824751210505921,0.3322995553227075,0.38646998629913942,0.43927356517438243,0.48919205000063709,0.53468789229255609,0.5742178234649028,0.60624701361898448,0.62926455809344151,0.64180124527536708,0.64245093967618705,0.62989760605330591,0.60295127941807047,0.56059877293383575,0.50208013050946387,0.42701394929988473,0.3356271608692597,0.22925211323694378,0.1117600956847189,0],[0,0.0029177443498442121,0.013568814113283053,0.032685803204614186,0.060077589262630106,0.095119277720012649,0.13691125309938565,0.18435956414157478,0.23622493138258183,0.29115632662794144,0.34771602137929319,0.40439959628577871,0.45965290633988498,0.51188727337119644,0.55949381697816236,0.60085767128515133,0.63437280060141699,0.65845820444376224,0.67157650965468108,0.67225634550924962,0.65912062157439166,0.63092416648346705,0.58660678834001079,0.52537327419774948,0.44682452668292466,0.35119800545911878,0.23988787053937422,0.11694501301008524,0],[0,0.0030374352045452763,0.014125430034271958,0.034026630656601178,0.062542074544765125,0.099021232889410588,0.14252758645036417,0.19192230822009521,0.2459152813751681,0.30310005623796749,0.3619799262324937,0.42098875815761805,0.47850865332422465,0.53288576327099424,0.58244520857546001,0.62550587880670838,0.66039585594797112,0.68546928417698494,0.69912572466456302,0.69983344854657092,0.68615887478925874,0.65680575297064325,0.61067040031259878,0.54692498287612734,0.46515403163181895,0.36560474724407171,0.24972848054991509,0.12174229710420115,0],[0,0.003148089017266572,0.014640019674663676,0.035266221351598716,0.064820483313295166,0.10262857797554782,0.14771986868739645,0.19891404095534693,0.25487397897960518,0.31414199609847271,0.37516686069162575,0.43632538530055587,0.49594073116121834,0.55229880008659304,0.60366369677026366,0.64829306790163066,0.68445408746403291,0.71044094108147382,0.7245948859128124,0.72532839218707701,0.7111556534907002,0.68073319697824763,0.63291713269046534,0.56684946868481567,0.48209960038855187,0.37892373399020007,0.25882609306082327,0.12617737092038331,0],[0,0.0032503134692889821,0.015115409023767673,0.036411382791696242,0.066925327982612304,0.10596112355727944,0.15251661444222361,0.20537315908215234,0.2631502229781259,0.32434278560355334,0.38734924389007447,0.45049370238789932,0.51204487218152805,0.57023299504798852,0.62326580785089103,0.66934437974595506,0.70667961655223555,0.73351031284892065,0.74812386325252966,0.74888118787390279,0.73424823333262845,0.70283790165873539,0.65346915860523924,0.58525615159552102,0.49775429350543632,0.39122811002689389,0.26723066973801557,0.13027459070331179,0],[0,0.0033446875073833053,0.015554290442590449,0.037468600582878153,0.068868529311402221,0.10903774346043589,0.15694499001811424,0.21133624372672677,0.27079088576419863,0.33376019678354779,0.39859607058666563,0.46357395148759883,0.52691228196518602,0.58678991822040838,0.64136255810245257,0.68877903815328223,0.72719831718930716,0.75480805254740158,0.76984591272159553,0.77062522653980847,0.75556739882172863,0.7232450567014721,0.67244287417156179,0.60224927760243963,0.51220677112051727,0.40258756101773169,0.27498980978531201,0.13405716100058415,0],[0,0.0034317602322780582,0.015959217494714469,0.038444025983171148,0.070661393515726451,0.11187633852156402,0.16103076123270169,0.21683799017379743,0.27784042335122389,0.34244902338728883,0.40897277870116294,0.47564223800379779,0.54062946423406555,0.6020659034977871,0.65805924066432808,0.70671012067444527,0.74612957425795001,0.7744580777777772,0.78988742070157425,0.79068702250709544,0.77523719222150667,0.74207339797839011,0.68994867501571433,0.61792771857816076,0.52554112273708975,0.41306818016949542,0.28214865855771326,0.13754709011181149,0],[0,0.0035120505201080678,0.016332603185865088,0.039343471661951616,0.072314604474488897,0.11449382424704582,0.16479827565496555,0.22191118394758796,0.28434084472444821,0.35046104310715698,0.41854120420120372,0.48677047820957814,0.5532781612159996,0.61615198218994072,0.67345535294081516,0.72324448064156499,0.76358620124260568,0.79257748524459093,0.8083678167866275,0.80918612626831765,0.79337482803724502,0.75943512568718385,0.70609088016859956,0.632384904111151,0.53783680925218669,0.42273242266734945,0.28874987643808131,0.14076517491604229,0],[0,0.0035860471765376671,0.016676720680652221,0.040172413426498764,0.073838226902897597,0.11690613583755759,0.16827046983725644,0.22658671055019217,0.29033172431900756,0.35784503295874981,0.427359599469605,0.49702642060844704,0.56493537792489845,0.6291339100618446,0.68764462615511468,0.73848277890698721,0.77967447373875232,0.80927658553762294,0.82539960925801392,0.82623515999669139,0.81009072783254699,0.77543593767844043,0.72096776305190768,0.6457088492574008,0.54916868655906592,0.43163912422607459,0.29483365150866897,0.14373100704911604,0],[0,0.0036542094759621246,0.016993705810097775,0.040935996262356458,0.075241717454850046,0.11912824576618647,0.17146889461660225,0.23089358953136524,0.29585024567447904,0.36464682308679808,0.43548269756255542,0.50647372066769758,0.5756734671049647,0.64109226193080104,0.70071512874422415,0.75251959488224829,0.79449424668549251,0.82465902481547904,0.84108850919195044,0.84193994177959153,0.825488642035341,0.79017514605091776,0.73467165988350847,0.6579822516298145,0.5596070881207309,0.43984356599173335,0.30043774388258565,0.14646299451519273,0],[0,0.0037169679757377357,0.017285560858169159,0.041639043454682265,0.076533941488274818,0.12117419032255805,0.17441375332136685,0.23485902593617863,0.30093126735616238,0.37090937801568452,0.44296180924376699,0.51517205367076324,0.58556025750211893,0.65210257451446518,0.71274942249211692,0.76544359421431341,0.80813913139457394,0.83882196855592006,0.85553361787075555,0.85639967321941013,0.83966583387306526,0.8037458532181837,0.74728913337681657,0.66928263800966037,0.5692179496614499,0.44739757254750928,0.30559755264726407,0.14897839432160284,0],[0,0.0037747255226424632,0.017554159242270672,0.042286067863044154,0.077723193788581585,0.12305710242373333,0.17712394899806999,0.23850847389888677,0.30560740443963375,0.37667289708229479,0.44984494292729621,0.52317725421274208,0.59465921241886399,0.66223552300368027,0.72382475552420611,0.77733773604828538,0.82069671437396552,0.85185632868757244,0.8688276584396506,0.86970717132486419,0.85271330673287515,0.81623516954260411,0.75890117508773225,0.67968254557133101,0.57806296329653739,0.45434963305762038,0.31034619861252588,0.15129335281841721,0],[0,0.0038278583888700602,0.01780125079612346,0.042881284647305964,0.078817221959260178,0.12478924864793317,0.17961713771639304,0.24186570842145055,0.30990912048252289,0.38197492779477549,0.45617694005724513,0.53054147364927151,0.60302960867547484,0.67155712036058834,0.73401328014057832,0.78827950696523497,0.83224880431446391,0.86384701995394131,0.88105723737825237,0.8819491302471747,0.86471606078356256,0.82772445897925895,0.76958343380403638,0.6892497264310915,0.58619975149894488,0.4607450380026954,0.31471461770848685,0.15342295122980004,0],[0,0.0038767174898941279,0.018028467433377195,0.043428624910654363,0.079823251498216188,0.12638206893724555,0.18190978571582167,0.24495290232506559,0.31386482612460259,0.38685048736094191,0.46199962024413843,0.53731334889258198,0.61072672846873766,0.68012893097995031,0.74338228634824577,0.79834117177969166,0.84287169687637054,0.87487323475331591,0.89230312481604679,0.893206401879304,0.87575336809195259,0.83828960242316186,0.77940646039457318,0.69804736693744485,0.59368205360344484,0.46662602576952777,0.31873166111455409,0.15538125446675968,0],[0,0.0039216296479152573,0.01823732902320347,0.04393174985326681,0.080748011812681639,0.12784621778635394,0.1840172286912142,0.24779070608188719,0.31750098137835242,0.39133218876533798,0.46735193183356849,0.5435381775253707,0.61780205841171587,0.68800829234753536,0.75199444413421135,0.8075900337241616,0.85263644938679473,0.88500872826557864,0.90264054533971261,0.90355428695766271,0.88589905803655467,0.84800127091322941,0.7884359618228256,0.70613431516925518,0.60055991929142782,0.47203193472749644,0.32242419913612269,0.15718136176689804,0],[0,0.0039628988732995632,0.018429249349557194,0.044394065127526638,0.081597762604575949,0.12919160601779006,0.18595373192259157,0.25039832878355306,0.32084219937613234,0.39545036864162386,0.4722701046189266,0.54925809540828296,0.62430349140782637,0.69524853985490931,0.75990804918848232,0.81608869833865405,0.86160915944862426,0.89432210763919862,0.9121394729415172,0.91306283030908153,0.89522180678548124,0.85692520272665307,0.79673305877762235,0.71356531167342641,0.60687990483090737,0.47699935747054278,0.32581722656046824,0.15883545805526597,0],[0,0.0040008076431172299,0.018605542056951734,0.044818735160751258,0.082378320196154861,0.13042744246264623,0.18773255026884936,0.25279361892646823,0.32391134988256876,0.39923321485557861,0.47678780220853423,0.55451225388545511,0.63027552806806042,0.70189923110544938,0.76717726807099518,0.82389533676300553,0.86985124291898441,0.90287712052377345,0.9208649253002239,0.92179711542961884,0.90378542611925705,0.86512247984618618,0.80435454272080931,0.72039121968040443,0.61268526887241948,0.48156229471008688,0.32893396777421197,0.16035486518898556,0],[0,0.0040356181610870191,0.018767426509763502,0.045208697269622088,0.08309508347280041,0.13156227503511703,0.18936598728896969,0.25499314402221401,0.32672966130154024,0.402706892232639,0.48093627217686907,0.55933699441292217,0.63575947519895426,0.70800636695823427,0.77385237981303112,0.83106394520009286,0.87741970784500156,0.91073293940638667,0.92887725378221386,0.92981755477924988,0.9116491480532225,0.87264980040671414,0.81135312919662594,0.72665925197161052,0.61801616539742477,0.48575230692984878,0.3317959803520415,0.1617500924566117,0],[0,0.0040675735872846945,0.018916033510925256,0.045566675435897201,0.083753059203237085,0.13260403082133604,0.19086545294444507,0.25701226829747009,0.32931682023520426,0.4058956652682349,0.48474449261246982,0.56376601899630285,0.64079363952725654,0.71361260726733333,0.77998001172069154,0.83764459815246173,0.88436742182567085,0.91794443912447554,0.93623242648317673,0.93718017311008039,0.91886790262958251,0.87955974460366504,0.81777770506217617,0.73241319230252189,0.62290983203634398,0.48959866240126593,0.33442325615951513,0.16303088586561257,0],[0,0.0040968992291439861,0.019052410840612377,0.045895193648506534,0.084356886562744982,0.13356005490633874,0.19224151948540633,0.25886522794818095,0.3316910679092101,0.40882201697557824,0.48823931405296084,0.56783055526362591,0.64541351532673363,0.71875747983028238,0.78560336775600215,0.84368369368783902,0.89074337095798828,0.9245624656434408,0.94298230236051261,0.94393688187625213,0.92549258696541081,0.88590103223143624,0.8236735679358399,0.73769360985603005,0.62740077245891757,0.49312848053983649,0.33683431927345842,0.1642062758784309,0],[0,0.0041238036877649931,0.019177528587088849,0.046196588744982302,0.084910860736134297,0.13443714774403537,0.19350397523961224,0.26056520356979385,0.33386929297953616,0.41150676327366431,0.49144559609393534,0.57155951534376581,0.64965196500424127,0.72347758149572505,0.79076244834796761,0.84922418950100675,0.89659290906607658,0.93063409474832293,0.94917489507885999,0.95013574334656181,0.93157032420457209,0.89171877055763815,0.82908265666033287,0.74253806564839275,0.63152093192032943,0.49636686988198686,0.33904632022787812,0.16528462335723965,0],[0,0.0041484799554961059,0.019292284250953279,0.046473022707034725,0.085418955517420958,0.13524160093868706,0.19466187611501379,0.26212438950868239,0.33586712039435795,0.41396916251294719,0.49438633819096339,0.57497964799138257,0.65353939200956901,0.72780677072250943,0.79549426086005159,0.85430582894132201,0.90195799633625218,0.93620287973919081,0.95485462564026091,0.95582122349036225,0.93714471146229572,0.89705469166087193,0.83404377196940349,0.74698131016142455,0.63529986534533778,0.49933706019691443,0.34107512625373576,0.16627366355570986,0],[0,0.0041711064622852343,0.019397507611139383,0.046726494382219978,0.085884844854640624,0.13597923135624704,0.19572359469838685,0.26355405997652614,0.33769899610820342,0.41622701988879873,0.49708280435628982,0.57811568361128518,0.65710390567455046,0.73177635115090456,0.79983302023388358,0.85896535649018324,0.90687742681357042,0.94130908756510934,0.96006256322256911,0.96103443305977232,0.94225605619669783,0.90194737869053776,0.83859278685469751,0.75105547175001497,0.63876489756691679,0.50206052843198223,0.3429354073066932,0.16718054805742047,0],[0,0.0041918480694923699,0.019493965346588132,0.046958850617047763,0.086311923312869382,0.13665541352292668,0.19669686688865803,0.26486463184499959,0.33937826754249878,0.41829678661223069,0.49955464159434748,0.58099047200093001,0.66037147777538563,0.73541524595646346,0.80381033955838221,0.86323672241909211,0.91138704447546992,0.94598992310151186,0.96483665392504625,0.96581335656683065,0.94694160071177813,0.9064324807658406,0.84276284636982868,0.75479023558945768,0.64194127551910651,0.50455711833423023,0.34464071777529182,0.16801188460848537,0],[0,0.004210857010786561,0.019582365411838866,0.047171796797306209,0.086703325447690008,0.13727511029869874,0.19758883604723743,0.26606572409695683,0.34091725976199039,0.42019365380026874,0.50181999203116756,0.5836251127588159,0.66336609075879716,0.73875016292041074,0.80745541049201919,0.86715127655068824,0.91551994780057033,0.95027974148591499,0.96921193733439126,0.97019306906875535,0.95123573470674838,0.91054291643249219,0.84658455679587219,0.75821301309472311,0.6448523123263491,0.50684515370263594,0.34620357383857747,0.16877377482929098,0],[0,0.0042282737804698756,0.01966336116813238,0.047366906799441701,0.087061944096157917,0.1378429018369057,0.19840609468143319,0.26716621395575535,0.34232734739477666,0.42193164112016179,0.50389559877851164,0.58603907840625558,0.66610987768598817,0.74180575027665119,0.8107951736039134,0.87073795119330566,0.91930668290710027,0.95421024858928694,0.97322075099005123,0.97420594084023415,0.95517019594907671,0.91430906575118309,0.85008616423715899,0.7613491018733578,0.6475195233417721,0.50894154531235591,0.347635526501335,0.16947184981907468,0],[0,0.004244227970121207,0.019737555274178215,0.047545632362995735,0.087390447603650598,0.13836301285908065,0.19915472370284337,0.26817428974913604,0.34361902236823744,0.42352368027652415,0.50579690563913071,0.58825033034627194,0.66862325403505851,0.74460474349204475,0.81385447880496475,0.87402343343291722,0.92277542545508295,0.95781068982456219,0.97689292295432273,0.97788183013846475,0.95877425927294624,0.91775895121089535,0.85329372282687377,0.76422183637277996,0.64996275427115291,0.51086189161842033,0.3489472303803412,0.17011130368913011,0],[0,0.0042588390548674426,0.019805503342666699,0.047709311898746325,0.087691296013523351,0.13883933828760631,0.19984032932207979,0.26909750059027626,0.34480195756672011,0.42498169347188541,0.50753815080897169,0.5902754278408453,0.67092504156786426,0.74716810320933646,0.81665623611975469,0.87703232705173007,0.92595215159655908,0.96110802758737746,0.98025595278819766,0.98124826436220169,0.96207491419849833,0.92091840774979006,0.85623125280533507,0.76685272945740568,0.65220030158279785,0.51262057339626232,0.35014850834913652,0.17069692507704617,0]],\"type\":\"surface\",\"frame\":null}],\"highlight\":{\"on\":\"plotly_click\",\"persistent\":false,\"dynamic\":false,\"selectize\":false,\"opacityDim\":0.20000000000000001,\"selected\":{\"opacity\":1},\"debounce\":0},\"shinyEvents\":[\"plotly_hover\",\"plotly_click\",\"plotly_selected\",\"plotly_relayout\",\"plotly_brushed\",\"plotly_brushing\",\"plotly_clickannotation\",\"plotly_doubleclick\",\"plotly_deselect\",\"plotly_afterplot\",\"plotly_sunburstclick\"],\"base_url\":\"https://plot.ly\"},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n:::\n\n::: {.content-visible unless-format=\"html\"}\n::: callout-note\n## Interactive content\n\nThe 3D surface plot is interactive and only available in the online edition of the book: <https://r4pde.net/prediction-disease-modeling.html>.\n:::\n:::\n\n#### Magarey's generic infection model\n\nIn the early 2000s, Magarey and collaborators [@magarey2005] proposed a generic infection model for foliar fungal pathogens, designed to predict infection periods based on limited data on temperature and wetness requirements. The model uses cardinal temperatures (minimum, optimum, maximum) and the minimum wetness duration (Wmin) necessary for infection. The model can incorporate inputs based on estimated cardinal temperatures and surface wetness duration. These values are available for numerous pathogens and can be consulted in the literature (See table 2 of the paper by @magarey2005).\n\nThe model utilizes a temperature response function, which is adjusted to the pathogen's minimum and optimum wetness duration needs, allowing it to be broadly applicable even with limited data on specific pathogens. The model was validated with data from 53 studies, showing good accuracy and adaptability, even for pathogens lacking comprehensive data [@magarey2005].\n\nThe function is given by\n\n$f(T) = \\left( \\frac{T_{\\text{max}} - T}{T_{\\text{max}} - T_{\\text{opt}}} \\right) \\times \\left( \\frac{T - T_{\\text{min}}}{T_{\\text{opt}} - T_{\\text{min}}} \\right)^{\\frac{T_{\\text{opt}} - T_{\\text{min}}}{T_{\\text{max}} - T_{\\text{opt}}}}$\n\nwhere $T$ is the temperature, $T_{\\text{min}}$ is the minimum temperature, $T_{\\text{opt}}$ is the optimum temperature, and $T_{\\text{max}}$ is the maximum temperature for infection. This is the beta function of @yin1995 (their Eq. 8b with $\\beta = 1$), scaled so that $f(T) = 1$ at the optimum temperature. It is zero at $T_{\\text{min}}$ and $T_{\\text{max}}$ and reaches its maximum exactly at $T_{\\text{opt}}$.\n\nThe wetness duration requirement is given by\n\n$W(T) = \\frac{W_{\\text{min}}}{f(T)} \\leq W_{\\text{max}}$\n\nwhere $W_{\\text{min}}$ is the minimum wetness duration requirement, and $W_{\\text{max}}$ is an optional upper limit on $W(T)$.\n\nLet's write the functions for estimating the required wetness duration at each temperature.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntemp_response <- function(T, Tmin, Topt, Tmax) {\n  if (T < Tmin || T > Tmax) {\n    return(0)\n  } else {\n    ((Tmax - T) / (Tmax - Topt)) * \n    ((T - Tmin) / (Topt - Tmin))^((Topt - Tmin) / (Tmax - Topt))\n  }\n}\n\n# Define the function to calculate wetness duration requirement W(T)\nwetness_duration <- function(T, Wmin, Tmin, Topt, Tmax, Wmax = Inf) {\n  f_T <- temp_response(T, Tmin, Topt, Tmax)\n  if (f_T == 0) {\n    return(0)  # Infinite duration required if outside temperature range\n  }\n  W <- Wmin / f_T\n  return(min(W, Wmax))  # Apply Wmax as an upper limit if specified\n}\n```\n:::\n\n\nLet's set the parameters for the fungus *Venturia inaequalis*, the cause of apple scab.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Parameters for Venturia inaequalis (apple scab)\nT <- seq(0, 35, by = 0.5) \nWmin <- 6                  \nTmin <- 1                  \nTopt <- 20                 \nTmax <- 35                 \nWmax <- 40.5                \n\n# Calculate wetness duration required at each temperature\nW_T <- sapply(T, wetness_duration, Wmin, Tmin, Topt, Tmax, Wmax)\n\ntemperature_data_applescab <- data.frame(\n  Temperature = T,\n  Wetness_Duration = W_T\n)\n```\n:::\n\n\nAnd now the parameters for the fungus *Phakopsora pachyrhizi*, the cause of soybean rust in soybean.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Parameters for Phakopsora pachyrhizi\nT <- seq(0, 35, by = 0.5)  \nWmin <- 8                \nTmin <- 10                  \nTopt <- 23                 \nTmax <- 28                \nWmax <- 12                 \n\n# Calculate wetness duration required at each temperature\nW_T <- sapply(T, wetness_duration, Wmin, Tmin, Topt, Tmax, Wmax)\n\ntemperature_data_soyrust <- data.frame(\n  Temperature = T,\n  Wetness_Duration = W_T)\n```\n:::\n\n\nWe can produce the plots for each pathogen.\n\n\n::: {.cell}\n\n```{.r .cell-code}\napplescab <- ggplot(temperature_data_applescab, aes(x = Temperature, y = Wetness_Duration)) +\n  geom_line(color = \"black\", linewidth = 1, linetype =1) +\n  theme_r4pde(font_size = 14)+\n  labs(x = \"Temperature (°C)\", y = \"Wetness Duration (hours)\", \n       subtitle = \"Venturia inaequalis\")+\n  theme(plot.subtitle = element_text(face = \"italic\"))\n\nsoyrust <- ggplot(temperature_data_soyrust, aes(x = Temperature, y = Wetness_Duration)) +\n  geom_line(color = \"black\", linewidth = 1, linetype =1) +\n  theme_r4pde(font_size = 14)+\n  labs(x = \"Temperature (°C)\", y = \"Wetness Duration (hours)\", \n       subtitle = \"Phakopsora pachyrhizi\")+ \n  theme(plot.subtitle = element_text(face = \"italic\"))\n\nlibrary(patchwork)\napplescab | soyrust\n```\n\n::: {.cell-output-display}\n![Wetness duration required for infection as a function of temperature, estimated with the generic infection model of @magarey2005 for Venturia inaequalis (left) and Phakopsora pachyrhizi (right)](prediction-disease-modeling_files/figure-html/fig-magarey-wetness-1.png){#fig-magarey-wetness width=672}\n:::\n:::\n\n\n### Latent period models\n\nThe latent period can be defined as \"the length of time between the start of the infection process by a unit of inoculum and the start of production of infectious units\" [@madden2007]. The latent period, analogous to the reproductive maturity age of nonparasitic organisms, defines the generation time between infections and is a key factor in pathogen development and epidemic progress in plant disease epidemiology [@plantdi1963]. As a critical trait of aggressiveness, especially in polycyclic diseases, it largely determines the potential number of infection cycles within a season, impacting the overall epidemic intensity [@lannou2012].\n\n#### Parabolic function\n\nThe effects of temperature on the length of the incubation and latent periods of hawthorn powdery mildew, caused by *Podosphaera clandestina*, were studied by @xu2000. In that work, the authors inoculated the leaves and, each day after inoculation, the upper surface of each leaf was examined for mildew colonies and conidiophores using a pen-microscope (×50). Sporulation was recorded at the leaf level, noting the number of colonies and the first appearance dates of colonies and sporulation for each leaf.\n\nThe latent period (LP) was defined as the time from inoculation to the first day of observed sporulation on the leaf. Due to the skewed distribution of LP across temperatures and inoculations, medians were used to summarize LP rather than means [@xu2000].\n\nLet's look at two plots extracted from the paper. The first, on the left-hand side, is the original number of days of the latent period of each evaluated temperature (note: the solid symbol is for constant temperature while the open circle is for fluctuating temperature). On the right-hand side, the relationship between temperature and rates of development of powdery mildew under constant temperature during the latent periods; the solid line indicates the fitted model. The rate of fungal development was calculated as the reciprocal of the corresponding observed incubation (in hours) and latent periods.\n\n![Source: @xu2000](imgs/modeling-latent.png){#fig-latent fig-align=\"center\"}\n\nThe latent period data in days for the solid black circle (constant temperature) above was extracted using the {digitize} R package.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlatent <- tibble::tribble(\n   ~T, ~days,\n  10L,   13L,\n  11L,   16L,\n  13L,    8L,\n  14L,    9L,\n  15L,    7L,\n  16L,    7L,\n  17L,    6L,\n  18L,    6L,\n  19L,    6L,\n  20L,    6L,\n  21L,    5L,\n  22L,    5L,\n  23L,    6L,\n  24L,    6L,\n  25L,    5L,\n  26L,    7L,\n  27L,    7L,\n  28L,   10L\n  )\n```\n:::\n\n\nLet's reproduce the two plots using the datapoints.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#|fig-width: 10\n#|fig-height: 4\nlibrary(ggplot2)\nlibrary(r4pde)\n\np_latent <- latent |> \n  ggplot(aes(T, days))+\n  geom_point()+\n  theme_r4pde()\n\nlatent_rate <- data.frame(\n  T = latent$T,  # Scale temperature\n  R = 1/latent$days/24\n)\n\np_latent_rate <- latent_rate |> \n  ggplot(aes(T, R))+\n  geom_point()+\n  theme_r4pde()\n\nlibrary(patchwork)\np_latent | p_latent_rate\n```\n\n::: {.cell-output-display}\n![Latent period (left) and rate of development, the inverse of the latent period (right), of powdery mildew at constant temperatures](prediction-disease-modeling_files/figure-html/fig-latent-data-1.png){#fig-latent-data width=672}\n:::\n:::\n\n\nWe will fit the parabolic function proposed by @bernard2013 which predicts a thermal response curve (developmental rate, R), which is the relationship between the inverse of latent period and temperature. We need to enter the values for optimum temperature (where latent period is shortest) and the minimum latent period. The model is given by:\n\n$R(T) = \\frac{k}{\\text{LP}_{\\text{min}} + \\text{a} \\times (T - T_{\\text{opt}})^2}$\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load necessary package\n#library(minpack.lm)\n\n# Define the model formula\n# model_formula <- R ~ (a + b * T)^(c * T)\nLPmin <- 5 # minimum latent period\nTopt <- 21 # Optimal temperature\nmodel_formula2 <- R ~ k / (LPmin + a * (T - Topt)^2)\n\n# Set initial parameter estimates\n#start_values <- list(a = 0.1, b = 0.01, c = 0.01)\nstart_values2 <- list(a = 0.1, k = 1)\n# Fit the model\n#fit_rate <- nlsLM(model_formula, data = latent_rate, start = start_values)\nfit_rate2 <- nls(model_formula2, data = latent_rate, start = start_values2)\n\n# View the summary of the fit\nsummary(fit_rate2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nFormula: R ~ k/(LPmin + a * (T - Topt)^2)\n\nParameters:\n  Estimate Std. Error t value Pr(>|t|)    \na 0.060274   0.010705    5.63 3.76e-05 ***\nk 0.039520   0.001464   26.99 9.05e-15 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.0006936 on 16 degrees of freedom\n\nNumber of iterations to convergence: 6 \nAchieved convergence tolerance: 3.165e-06\n```\n\n\n:::\n\n```{.r .cell-code}\nfit_rate2$m$getAllPars()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         a          k \n0.06027417 0.03952035 \n```\n\n\n:::\n\n```{.r .cell-code}\na <- fit_rate2$m$getAllPars()[1]\nk <- fit_rate2$m$getAllPars()[2]\n```\n:::\n\n\nNow we reproduce the plot with the fitted data. Note that the curve is not the same shown in the paper because we used a different equation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nT <- seq(10, 29, 0.1)\n#R <- (a + b * T)^(c * T)\nR <- k / (LPmin + a * (T - Topt)^2)\ndat2 <- data.frame(T, R)\n\ndat2 |>\n  ggplot(aes(T, R)) +\n  geom_line() +\n  geom_point(data = latent_rate, aes(T, R)) +\n  theme_r4pde(font_size = 16) +\n  labs(x = \"Temperature\", y = \"Inverse of the latent period (hour -1)\", \n       title = \"\")\n```\n\n::: {.cell-output-display}\n![Rate of development (inverse of the latent period) as a function of temperature; the line is the fitted parabolic function](prediction-disease-modeling_files/figure-html/fig-latent-fit-1.png){#fig-latent-fit width=672}\n:::\n:::\n\n\n## Field data\n\nWhile pathogen inoculum, host resistance, and agronomic factors are sometimes included alongside weather in empirically derived models using field data [@shah2013; @cao2015; @mehra2017], only a few models explicitly incorporate non-weather factors [@mehra2016; @paul2004]. In most cases, these models primarily rely on weather variables as predictors [@gonzález-domínguez2023]. This focus reflects the critical role of weather in driving key processes in the disease cycle, such as pathogen survival, dispersal, host infection, and reproduction [@dewolf2007]. Consequently, a primary objective for plant epidemiologists is to identify and quantify the relationships between weather conditions and measures of disease intensity [@shah2019; @eljarroudi2017; @pietravalle2003; @coakley1988; @delponte2006; @shah2013; @coakley1988a].\n\nIn modeling efforts, the disease variable can be represented either as a continuous measure (e.g., incidence or severity) or as categorical data, which may be binary (e.g., non-epidemic vs. epidemic) or multinomial (e.g., low, moderate, and high severity). This variability in response types informs the selection of suitable modeling techniques, ensuring that the model accurately captures the nature of the data and the relationships between weather variables and disease outcomes.\n\nIn this section, we demonstrate several modeling approaches that can be applied when field data is available. These examples will cover a range of techniques, starting with variable construction, which involves transforming raw weather data into summary measures that can effectively represent conditions relevant to disease outcomes. Next, variable selection methods will be explored to identify the most influential predictors, ensuring that models are both accurate and interpretable. The focus will then shift to model fitting, showing how different models, such as linear and logistic regression, can be used to capture relationships between weather variables and disease endpoints. Finally, model evaluation will be addressed, emphasizing metrics like accuracy, sensitivity, and area under the curve (AUC), which are crucial for assessing the predictive performance and reliability of the models developed.\n\nBelow is a typical workflow for developing a disease prediction model, starting with disease data collection and weather data retrieval. The process includes data pre-processing, feature engineering, variable selection, model fitting, cross-validation, model tuning, and evaluation, followed by interpretation. Iterative feedback between model evaluation and variable selection aims to optimize model performance.\n\n![Key steps for developing a plant disease prediction model](imgs/modeling-workflow.png){#fig-workflow fig-align=\"center\"}\n\n### Variable creation and selection\n\nVariable construction, particularly for weather-related variables, involves not only data transformation methods but also requires an understanding of how diseases respond to specific weather conditions at particular growth stages [@decól2024; @dewolf2003]. This approach ensures that the variables derived accurately capture biologically relevant processes, improving the realism and relevance of the model inputs.\n\nIn addition, data mining techniques are employed to systematically explore time-series data and identify potential weather-disease relationships [@shah2019; @pietravalle2003; @coakley1988]. These techniques involve creating lagged variables, moving averages, or window-based summaries that capture delayed or cumulative effects of weather on disease outcomes. By integrating system knowledge with data mining, researchers aim to construct variables that are both biologically meaningful and statistically robust, improving the chances of identifying predictors that enhance model accuracy and interpretability.\n\n#### Window-pane\n\n##### Variable construction\n\nWith regards to weather variable creation and selection for data-mining purposes, window-pane analysis, first introduced in the mid-1980s [@coakley1985], has been widely used in modeling studies in plant pathology [@pietravalle2003; @calverojr1996; @tebeest2008a; @gouache2015a; @coakley1988; @kriss2010; @dallalana2021; @coakley1988a]. This method aids in identifying weather conditions that are most strongly associated with disease outcomes by segmenting a continuous time series (e.g. daily temperature, relative humidity, and rainfall), into discrete, fixed-length windows.\n\nThe analysis involves summarizing conditions within each window (e.g., mean, sum, count) and correlating these summaries with disease outcomes, which may be expressed as continuous measures (e.g., severity) or as categorical variables (e.g., low vs. high levels). This approach allows users to set specific start and end times, as well as window lengths, enabling the exploration of different temporal relationships between weather and disease. By sliding the start and end points along the series, multiple overlapping windows are generated, making it possible to identify the most informative variables for modeling. The selected optimal fixed-time and fixed-window-length variables derived from this analysis serve as predictors in model development, helping to improve the accuracy and relevance of disease forecasting models.\n\nHere's an R code that demonstrates how the windows are defined over a 28-day period using four fixed window lengths (7, 14, 21, and 28 days), generating a total of 46 variables.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nlibrary(dplyr)\nlibrary(ggplot2)\n\n# Define total days and window lengths\nmax_days <- 28\nwindow_lengths <- c(7, 14, 21, 28)\n\n# Create an empty data frame for all sliding windows\nwindow_data <- data.frame()\n\n# Populate the data frame with start and end points for each window\nvar_id <- 1  # Variable ID for each window\n\nfor (length in sort(window_lengths)) {  # Sort window lengths from shortest to longest\n  for (start_day in 0:(max_days - length)) {\n    end_day <- start_day + length\n    window_data <- rbind(\n      window_data,\n      data.frame(\n        start = start_day,\n        end = end_day,\n        var_id = var_id,\n        window_length = length\n      )\n    )\n    var_id <- var_id + 1  # Increment variable ID\n  }\n}\n\n# Convert window_length to a factor for correct ordering in the legend\nwindow_data$window_length <- factor(window_data$window_length, levels = sort(unique(window_data$window_length)))\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwindow_data |> \n  ggplot(aes(x = start, xend = end, y = var_id, yend = var_id)) +\n  geom_segment(linewidth = 2) +  # Line segments for each window\n  scale_x_continuous(breaks = 0:max_days, limits = c(0, max_days)) +\n  scale_y_continuous(breaks = 1:var_id) +\n  labs(title = \"Window-pane\",\n    subtitle = \"Each variable of 7, 14, 21 and 28 days length over 28 days\",\n    x = \"Days\", y = \"Variable ID\", color = \"Window Length (days)\") +\n  r4pde::theme_r4pde(font_size = 14) +\n  theme(legend.position = \"right\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nIgnoring unknown labels:\n• colour : \"Window Length (days)\"\n```\n\n\n:::\n\n::: {.cell-output-display}\n![Fixed-length windows (7, 14, 21 and 28 days) generated over a 28-day period; each segment is one window-pane variable](prediction-disease-modeling_files/figure-html/fig-windowpane-design-1.png){#fig-windowpane-design width=768}\n:::\n:::\n\n\nThe window-pane analysis requires a spreadsheet program [@kriss2010] or a specific algorithm that automates the creation of sliding windows at defined starting and ending times relative to a reference date. In the seminal work, software was programmed in the FORTRAN language and named WINDOW [@coakley1985]. It enabled the creation of windows and the calculation of summary statistics, including correlation with disease severity. Building on the original idea, a Genstat 6.1 algorithm was developed in the early 2000s, incorporating further adjustments such as the implementation of bootstrapping analysis to validate correlations and misclassifications identified by window-pane [@pietravalle2003; @tebeest2008a]. More recently, window-pane analysis including variable creation and analysis has been conducted in R using custom-made scripts [@gouache2015a; @dallalana2021].\n\nI will demonstrate the `windowpane()` function of the {r4pde} package developed to facilitate the creation of variables using the window-pane approach. First, let's load a dataset that contains information on the disease, as well as metadata, including a key date that will be used as the starting point for window creation. The BlastWheat dataset, which is included in the {r4pde} package, was provided by @decól2024.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(r4pde)\nlibrary(dplyr)\ntrials <- BlastWheat\nglimpse(trials)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 143\nColumns: 10\n$ study      <dbl> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, …\n$ year       <dbl> 2012, 2012, 2012, 2012, 2012, 2013, 2013, 2013, 2013, 2014,…\n$ location   <chr> \"Dourados\", \"Palotina\", \"Londrina\", \"Planaltina\", \"Itaberá\"…\n$ state      <chr> \"MS\", \"PR\", \"PR\", \"DF\", \"SP\", \"MS\", \"MG\", \"DF\", \"SP\", \"MG\",…\n$ latitude   <dbl> -22.27516, -24.35483, -23.35916, -15.60387, -24.06832, -22.…\n$ longitude  <dbl> -54.81640, -53.75794, -51.16476, -47.71381, -49.15575, -54.…\n$ heading    <chr> \"10-05-2012\", \"09-06-2012\", \"01-06-2012\", \"03-05-2012\", \"15…\n$ inc_mean   <dbl> 93.30, 40.50, 100.00, 35.50, 7.71, 48.70, 22.00, 46.50, 68.…\n$ index_mean <dbl> 68.65, 11.73, 92.86, 6.36, 0.35, 9.17, 2.91, 10.41, 41.86, …\n$ yld_mean   <dbl> 1097.00, 1219.38, 495.12, 1747.44, 2148.31, 506.00, 1562.75…\n```\n\n\n:::\n:::\n\n\nWe can note that the heading date, which will be used as reference date in our analysis, is not defined as date object, which needs correction.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntrials$heading = as.Date(trials$heading, format = \"%d-%m-%Y\")\nglimpse(trials$heading)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Date[1:143], format: \"2012-05-10\" \"2012-06-09\" \"2012-06-01\" \"2012-05-03\" \"2012-04-15\" ...\n```\n\n\n:::\n:::\n\n\nThe weather data for our analysis will be downloaded from NASA POWER. Since we have multiple trials with different heading dates, a wrapper function for the `get_power()` function from the {nasapower} package was created, included in {r4pde}, and named `get_nasapower()`. This function enables the download of data for a period \"around\" the key date, which can be defined by the user. In our case, we will download data from 28 days before and 28 days after the heading date.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nweather_data <- get_nasapower(\n  data = trials,\n  days_around = 28,\n  date_col = \"heading\",\n  pars = c(\"T2M\", \"T2M_MAX\", \"T2M_MIN\", \"T2M_RANGE\", \"RH2M\", \n           \"PRECTOTCORR\", \"T2MDEW\", \"WS2M\", \"PS\", \"GWETTOP\", \n           \"GWETPROF\", \"CLRSKY_SFC_PAR_TOT\")\n)\n# See all parameters in the website: https://power.larc.nasa.gov/#resources\n\n# save the data for faster rendering\nwrite_csv(weather_data, \"data/weather_windowpane.csv\")\n```\n:::\n\n\nNow we can see the weather data and join the two dataframes.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# read the data\nweather_data <- readr::read_csv(\"data/weather_windowpane.csv\")\n\nglimpse(weather_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 8,151\nColumns: 14\n$ LON         <dbl> -54.8164, -54.8164, -54.8164, -54.8164, -54.8164, -54.8164…\n$ LAT         <dbl> -22.27516, -22.27516, -22.27516, -22.27516, -22.27516, -22…\n$ YEAR        <dbl> 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012…\n$ MM          <dbl> 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5…\n$ DD          <dbl> 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26…\n$ DOY         <dbl> 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114…\n$ YYYYMMDD    <date> 2012-04-12, 2012-04-13, 2012-04-14, 2012-04-15, 2012-04-1…\n$ T2M         <dbl> 24.31, 25.83, 24.99, 24.15, 22.72, 23.33, 23.76, 24.83, 24…\n$ RH2M        <dbl> 83.69, 77.62, 81.69, 82.69, 74.62, 74.44, 70.19, 67.75, 77…\n$ PRECTOTCORR <dbl> 0.02, 1.13, 11.00, 0.06, 0.00, 0.04, 0.00, 0.03, 24.08, 20…\n$ T2M_MAX     <dbl> 28.61, 31.01, 30.01, 29.43, 30.33, 30.69, 31.51, 32.49, 30…\n$ T2M_MIN     <dbl> 20.82, 20.43, 21.11, 19.04, 16.31, 17.37, 17.15, 17.69, 20…\n$ T2MDEW      <dbl> 21.19, 21.23, 21.38, 20.75, 17.47, 18.01, 17.29, 17.85, 20…\n$ study       <dbl> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1…\n```\n\n\n:::\n\n```{.r .cell-code}\n# apply a full join\ntrials_weather <- full_join(trials, weather_data) \n```\n:::\n\n\nWe are now ready to use the windowpane function to create new variables. The function has several arguments. Note the two date variables: `end_date`, which serves as the reference for sliding the windows, and `date_col`, which represents the date for each day in the time series. The `summary_type` specifies the statistic to be calculated, while the `direction` determines whether the sliding windows will move backward, forward, or in both directions relative to the end date. Lastly, the `group_by` argument specifies the index variable for the epidemic or study.\n\nWe will create new variables based on the mean daily temperature (T2M), with each variable representing the mean value over one of the four window lengths (7, 14, 21, and 28 days) defined in the `window_length` argument. We will only generate variables that cover periods before the heading date, using \"backward\" in the `direction` argument.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create window variables separated for each weather variable\n\nwp_T2M <- windowpane(\n  data = trials_weather,\n  end_date_col = heading,\n  date_col = YYYYMMDD,\n  variable = T2M,  \n  summary_type = \"mean\",\n  threshold = NULL,\n  window_lengths = c(7, 14, 21, 28),\n  direction = \"backward\",\n  group_by_cols = \"study\", \n)\n\nwpT2M_MIN_15 <- windowpane(\n    data = trials_weather,\n    end_date_col = heading,\n    date_col = YYYYMMDD,\n    variable = T2M_MIN,   \n    summary_type = \"below_threshold\",\n    threshold = 15,\n    window_lengths = c(7, 14, 21, 28),\n    direction = \"backward\",\n    group_by_cols = \"study\", \n  )\n\nwpT2M_MIN <- windowpane(\n    data = trials_weather,\n    end_date_col = heading,\n    date_col = YYYYMMDD,\n    variable = T2M_MIN,   \n    summary_type = \"mean\",\n    threshold = NULL,\n    window_lengths = c(7, 14, 21, 28),\n    direction = \"backward\",\n    group_by_cols = \"study\", \n  )\n\nwpT2M_MAX <- windowpane(\n    data = trials_weather,\n    end_date_col = heading,\n    date_col = YYYYMMDD,\n    variable = T2M_MAX,   \n    summary_type = \"mean\",\n    threshold = NULL,\n    window_lengths = c(7, 14, 21, 28),\n    direction = \"backward\",\n    group_by_cols = \"study\", \n  )\n\nwpPREC <- windowpane(\n    data = trials_weather,\n    end_date_col = heading,\n    date_col = YYYYMMDD,\n    variable = PRECTOTCORR,   \n    summary_type = \"sum\",\n    threshold = NULL,\n    window_lengths = c(7, 14, 21, 28),\n    direction = \"backward\",\n    group_by_cols = \"study\", \n  )\n\nwpRH2M <- windowpane(\n    data = trials_weather,\n    end_date_col = heading,\n    date_col = YYYYMMDD,\n    variable = RH2M,   \n    summary_type = \"mean\",\n    threshold = NULL,\n    window_lengths = c(7, 14, 21, 28),\n    direction = \"backward\",\n    group_by_cols = \"study\", \n  )\n\n# combine all datasets\nwp_all <- cbind(wp_T2M, wpT2M_MIN_15, wpT2M_MIN, wpT2M_MAX, wpPREC, wpRH2M)\n```\n:::\n\n\n##### Correlations and multiple hypothesis test\n\nThe window-pane analysis begins by quantifying the associations between each summary weather variable and disease response using a specific correlation coefficient (Pearson or Spearman). Usually, Spearman's rank correlation can be preferred due to its ability to measure monotonic relationships and its robustness to outliers. In other cases, Spearman was used because the disease data was ordinal [@kriss2010].\n\nIn a recent study, @dallalana2021, differing from @kriss2010, proposed the estimation of the precision of these correlations via bootstrapping, where a high number of samples (e.g. 1000) are randomly drawn (with replacement) from the original dataset. For each bootstrap sample, correlations between weather variables and disease outcomes are calculated, and the average across samples is used as the final measure of association. This approach ensures a more reliable estimation of the correlations by capturing variability and improving statistical robustness.\n\nThe window-pane analysis involves numerous tests, as each time window generates a separate test statistic. Because many tests are conducted, the global significance level becomes higher than the critical significance level set for individual tests, increasing the risk of false positives [@kriss2010]. Additionally, the correlations among test statistics are influenced by overlapping time windows, shared data, and large-scale climatic patterns. To address this issue, @kriss2010 proposed the use of the Simes' method, which tests the global null hypothesis that none of the individual correlations are significant. Simes' method orders p-values and rejects the global null hypothesis if any adjusted p-value meets a specific threshold.\n\nWhile this method indicates whether at least one correlation is significant, it does not provide significance for individual correlations. Therefore, the authors proposed that the individual correlation coefficients should be compared against a more stringent significance level (α = 0.005 instead of 0.05), reducing the likelihood of false positives but increasing false negatives. Although this adjustment is independent of the Simes' method, there was a general alignment: significant global results often corresponded to significant individual correlations, and non-significant global results typically lacked significant individual correlations [@kriss2010].\n\nLet's calculate the bootstrapped correlation coefficients combined with the Simes' method. First, we need to subset our variables to the specific combination of weather and window.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n  T2M_MIN_7 = wp_all |> dplyr::select(contains(\"length7_T2M_MIN_mean\"))\n  T2M_MIN_14 = wp_all |> dplyr::select(contains(\"length14_T2M_MIN_mean\"))\n  T2M_MIN_21 = wp_all |> dplyr::select(contains(\"length21_T2M_MIN_mean\"))\n  T2M_MIN_28 = wp_all |> dplyr::select(contains(\"length28_T2M_MIN_mean\"))\n \n  T2M_MAX_7 = wp_all |> dplyr::select(contains(\"length7_T2M_MAX_mean\"))\n  T2M_MAX_14 = wp_all |> dplyr::select(contains(\"length14_T2M_MAX_mean\"))\n  T2M_MAX_21 = wp_all |> dplyr::select(contains(\"length21_T2M_MAX_mean\"))\n  T2M_MAX_28 = wp_all |> dplyr::select(contains(\"length28_T2M_MAX_mean\"))\n  \n  T2M_7 = wp_all |> dplyr::select(contains(\"length7_T2M_mean\"))\n  T2M_14 = wp_all |> dplyr::select(contains(\"length14_T2M_mean\"))\n  T2M_21 = wp_all |> dplyr::select(contains(\"length21_T2M_mean\"))\n  T2M_28 = wp_all |> dplyr::select(contains(\"length28_T2M_mean\"))\n  \n  RH2M_7 = wp_all |> dplyr::select(contains(\"length7_RH2M_mean\"))\n  RH2M_14 = wp_all |> dplyr::select(contains(\"length14_RH2M_mean\"))\n  RH2_21 = wp_all |> dplyr::select(contains(\"length21_RH2M_mean\"))\n  RH2_28 = wp_all |> dplyr::select(contains(\"length28_RH2M_mean\"))\n  \n  PRECTOTCORR_7 = wp_all |> dplyr::select(contains(\"length7_PRECTOTCORR\"))\n  PRECTOTCORR_14 = wp_all |> dplyr::select(contains(\"length14_PRECTOTCORR\"))\n  PRECTOTCORR_21 = wp_all |> dplyr::select(contains(\"length21_PRECTOTCORR\"))\n  PRECTOTCORR_28 = wp_all |> dplyr::select(contains(\"length28_PRECTOTCORR\"))\n  \n  T2M_MINb_7 = wp_all |> dplyr::select(contains(\"length7_T2M_MIN_below\"))\n  T2M_MINb_14 = wp_all |> dplyr::select(contains(\"length14_T2M_MIN_below\"))\n  T2M_MINb_21 = wp_all |> dplyr::select(contains(\"length21_T2M_MIN_below\"))\n  T2M_MINb_28 = wp_all |> dplyr::select(contains(\"length28_T2M_MIN_below\"))\n```\n:::\n\n\nNow, we can use the `windowpane_tests()` function from the {r4pde} package to analyze each of the datasets created above. This function will compute the bootstrapped correlation coefficients for the variables of interest and apply the Simes' procedure to account for multiple testing, providing adjusted P-values for more robust statistical inference.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(boot)\ndata <- T2M_MINb_7 \ndata$inc <- trials$inc_mean \nresponse_var <- 'inc'  \nresults <- windowpane_tests(data, response_var, corr_type = \"spearman\", R = 1000)\nresults_TMINb <- results$results\n\nresults\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$results\n                                     variable correlation      p_value\n1  bw_length7_T2M_MIN_below_threshold_-18_-24  -0.5295915 1.040432e-11\n2  bw_length7_T2M_MIN_below_threshold_-17_-23  -0.5136581 5.359609e-11\n3  bw_length7_T2M_MIN_below_threshold_-15_-21  -0.5116609 6.543248e-11\n4  bw_length7_T2M_MIN_below_threshold_-10_-16  -0.5063934 1.100732e-10\n5  bw_length7_T2M_MIN_below_threshold_-11_-17  -0.5054218 1.210402e-10\n6  bw_length7_T2M_MIN_below_threshold_-16_-22  -0.5038720 1.407514e-10\n7  bw_length7_T2M_MIN_below_threshold_-12_-18  -0.4972482 2.659657e-10\n8  bw_length7_T2M_MIN_below_threshold_-19_-25  -0.4951918 3.231718e-10\n9   bw_length7_T2M_MIN_below_threshold_-9_-15  -0.4913413 4.638201e-10\n10  bw_length7_T2M_MIN_below_threshold_-7_-13  -0.4882483 6.180090e-10\n11   bw_length7_T2M_MIN_below_threshold_-3_-9  -0.4793727 1.386299e-09\n12    bw_length7_T2M_MIN_below_threshold_0_-6  -0.4757057 1.922737e-09\n13  bw_length7_T2M_MIN_below_threshold_-8_-14  -0.4743890 2.160334e-09\n14 bw_length7_T2M_MIN_below_threshold_-14_-20  -0.4742346 2.189972e-09\n15  bw_length7_T2M_MIN_below_threshold_-4_-10  -0.4735015 2.336183e-09\n16   bw_length7_T2M_MIN_below_threshold_-2_-8  -0.4730773 2.425031e-09\n17   bw_length7_T2M_MIN_below_threshold_-1_-7  -0.4698400 3.218863e-09\n18  bw_length7_T2M_MIN_below_threshold_-6_-12  -0.4663226 4.364062e-09\n19 bw_length7_T2M_MIN_below_threshold_-13_-19  -0.4630281 5.785628e-09\n20  bw_length7_T2M_MIN_below_threshold_-5_-11  -0.4594875 7.807700e-09\n21 bw_length7_T2M_MIN_below_threshold_-20_-26  -0.4334293 6.401965e-08\n22 bw_length7_T2M_MIN_below_threshold_-21_-27  -0.4291061 8.925631e-08\n    mean_corr    sd_corr median_corr rank  m simes_threshold significant_simes\n1  -0.5278506 0.05898316  -0.5303406    1 22     0.002272727              TRUE\n2  -0.5121495 0.06171704  -0.5122129    2 22     0.004545455              TRUE\n3  -0.5123503 0.06203823  -0.5143697    3 22     0.006818182              TRUE\n4  -0.5042803 0.06587020  -0.5047320    4 22     0.009090909              TRUE\n5  -0.5068119 0.06332468  -0.5087314    5 22     0.011363636              TRUE\n6  -0.5052815 0.06169134  -0.5090545    6 22     0.013636364              TRUE\n7  -0.4951691 0.06493748  -0.4964268    7 22     0.015909091              TRUE\n8  -0.4927008 0.06055456  -0.4949095    8 22     0.018181818              TRUE\n9  -0.4925187 0.06488104  -0.4960671    9 22     0.020454545              TRUE\n10 -0.4889771 0.06779316  -0.4920826   10 22     0.022727273              TRUE\n11 -0.4764529 0.06494004  -0.4781866   11 22     0.025000000              TRUE\n12 -0.4732224 0.06555903  -0.4747327   12 22     0.027272727              TRUE\n13 -0.4715110 0.06680684  -0.4734682   13 22     0.029545455              TRUE\n14 -0.4705602 0.06377271  -0.4738811   14 22     0.031818182              TRUE\n15 -0.4717013 0.06754810  -0.4720665   15 22     0.034090909              TRUE\n16 -0.4730070 0.06207360  -0.4746043   16 22     0.036363636              TRUE\n17 -0.4693673 0.06440652  -0.4724115   17 22     0.038636364              TRUE\n18 -0.4613088 0.06702970  -0.4651864   18 22     0.040909091              TRUE\n19 -0.4619740 0.07048628  -0.4663896   19 22     0.043181818              TRUE\n20 -0.4629481 0.06818838  -0.4618622   20 22     0.045454545              TRUE\n21 -0.4318661 0.06732984  -0.4336915   21 22     0.047727273              TRUE\n22 -0.4295919 0.06759751  -0.4330253   22 22     0.050000000              TRUE\n   individual_significant\n1                    TRUE\n2                    TRUE\n3                    TRUE\n4                    TRUE\n5                    TRUE\n6                    TRUE\n7                    TRUE\n8                    TRUE\n9                    TRUE\n10                   TRUE\n11                   TRUE\n12                   TRUE\n13                   TRUE\n14                   TRUE\n15                   TRUE\n16                   TRUE\n17                   TRUE\n18                   TRUE\n19                   TRUE\n20                   TRUE\n21                   TRUE\n22                   TRUE\n\n$summary_table\n               Metric        Value\n1 Global P-value (Pg) 2.288950e-10\n2     Max Correlation 5.295915e-01\n\n$global_significant\n[1] TRUE\n```\n\n\n:::\n:::\n\n\nThe window-pane tests show negative correlations between disease incidence and the number of days with TMIN below 15 °C in the 7-day windows. The mean correlations range from -0.53 to -0.43.\n\nThe global P-value in the output accounts for multiple testing with Simes' procedure. A low global P-value indicates that at least one window is significantly associated with the response. Together, these results suggest that cold conditions in the weeks before heading are associated with a lower incidence of wheat blast.\n\nLet's apply the test function to 7-day long windows for three other variables: relative humidity, precipitation and maximum temperature.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(r4pde)\ndata1 <- RH2M_7 \ndata1$inc <- trials$inc_mean \nresponse_var <- 'inc'  \nresults1 <- windowpane_tests(data1, response_var, corr_type = \"spearman\", R = 1000)\nresults_RH <- results1$results\n\n\ndata2 <- PRECTOTCORR_7 \ndata2$inc <- trials$inc_mean \nresponse_var <- 'inc'  \nresults2 <- windowpane_tests(data2, response_var, corr_type = \"spearman\", R = 1000)\nresults_PREC <- results2$results\n\n\ndata3 <- T2M_MAX_7 # enter the dataset\ndata3$inc <- trials$inc_mean \nresponse_var <- 'inc'  \nresults3 <- windowpane_tests(data3, response_var, corr_type = \"spearman\", R = 1000)\nresults_TMAX <- results3$results\n```\n:::\n\n\nThe first variable in the results dataframe contains the name of the variable. We can extract the first and last day of each window (relative to the heading date) from the variable name using the `extract` function, which allows for regex-based extraction into new columns. We then keep the earliest day of each window as its starting day (`start`). The column names created by `windowpane()` start with the direction of the windows (`bw_` for backward), so we select variables with `contains()` instead of `starts_with()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Use strcapture to extract components into new columns\ndf_TMINb7 <- results_TMINb |>\n  extract(variable, into = c(\"variable_prefix\", \"low\", \"high\"), \n          regex = \"^(.*)_(-?\\\\d+)_(-?\\\\d+)$\", convert = TRUE) |>\n  dplyr::mutate(start = pmin(low, high))\n\n\ndf_RH7 <- results_RH |>\n  extract(variable, into = c(\"variable_prefix\", \"low\", \"high\"), \n          regex = \"^(.*)_(-?\\\\d+)_(-?\\\\d+)$\", convert = TRUE) |>\n  dplyr::mutate(start = pmin(low, high))\n\n\ndf_PREC7 <- results_PREC |>\n  extract(variable, into = c(\"variable_prefix\", \"low\", \"high\"), \n          regex = \"^(.*)_(-?\\\\d+)_(-?\\\\d+)$\", convert = TRUE) |>\n  dplyr::mutate(start = pmin(low, high))\n\ndf_TMAX7 <- results_TMAX |>\n  extract(variable, into = c(\"variable_prefix\", \"low\", \"high\"), \n          regex = \"^(.*)_(-?\\\\d+)_(-?\\\\d+)$\", convert = TRUE) |>\n  dplyr::mutate(start = pmin(low, high))\n```\n:::\n\n\nNow we can plot the mean correlation for the start day of each window.\n\n\n::: {.cell}\n\n```{.r .cell-code}\np_TMIN <- df_TMINb7 |> \n  ggplot(aes(start, mean_corr, fill = p_value))+\n  ylim(-1, 1)+\n  geom_col()+\n  theme_r4pde(font_size = 12)+\n  labs(title = \"N. days TMIN < 15C\",\n       subtitle = \"7-day window\",\n       y = \"Spearman's correlation\",\n       x = \"Day relative to heading date \")\n\np_RH <- df_RH7 |> \n  ggplot(aes(start, mean_corr, fill = p_value))+\n  ylim(-1, 1)+\n  geom_col()+\n  theme_r4pde(font_size = 12)+\n  labs(title = \"Relative humidity\", \n       subtitle = \"7-day window\",\n       y = \"Spearman's correlation\",\n       x = \"Day relative to heading date \")\n\np_TMAX <- df_TMAX7 |> \nggplot(aes(start, mean_corr, fill = p_value))+\n  ylim(-1, 1)+\n  geom_col()+\n  theme_r4pde(font_size = 12)+\n  labs(title = \"Max. temperature\", \n       subtitle = \"7-day window\",\n       y = \"Spearman's correlation\",\n       x = \"Day relative to heading date \")\n\n\np_PREC <- df_PREC7 |> \n  ggplot(aes(start, mean_corr, fill = p_value))+\n  ylim(-1, 1)+\n  geom_col()+\n  theme_r4pde(font_size = 12)+\n  labs(title = \"Cumulative rainfall\", \n       subtitle = \"7-day window\",\n       y = \"Spearman's correlation\",\n       x = \"Day relative to heading date \")\n    \nscale_common <- scale_fill_viridis_c(limits = c(0, 1), \n                                     na.value = \"grey90\")\n\np_TMIN <- p_TMIN + scale_common\np_TMAX <- p_TMAX + scale_common\np_RH <- p_RH + scale_common\np_PREC <- p_PREC + scale_common\n\n# Combine plots using patchwork and collect guides\n(p_TMIN | p_TMAX) / (p_RH | p_PREC) + \n  plot_layout(guides = \"collect\")\n```\n\n::: {.cell-output-display}\n![Mean Spearman correlation between wheat blast incidence and 7-day window-pane variables, by starting day of the window relative to heading; the fill indicates the P-value](prediction-disease-modeling_files/figure-html/fig-windowpane-corr-1.png){#fig-windowpane-corr width=672}\n:::\n:::\n\n\n**Interpretation**. All 7-day-length variables but maximum temperature were strongly associated with the incidence of wheat blast. These three variables can be used as candidates for developing prediction models.\n\n#### Functional data analysis\n\nFunctional Data Analysis (FDA) is a statistical approach used to analyze and model data that varies continuously over time or space. It represents entire data sequences (e.g., time series) as smooth functions, allowing for the exploration of trends, patterns, and relationships in complex, continuous processes rather than relying on discrete, segmented data points [@ramsay2005functional; @Gertheiss2024].\n\nIn the FDA framework, scalar-on-function and function-on-scalar models are two types of FDA models, designed to examine relationships between functional predictors and outcomes. Function-on-scalar models use single values (e.g., mean daily relative humidity) as predictors to explain the shape of an entire outcome curve (e.g. disease). Meanwhile, in scalar-on-function models, time series data (e.g., daily temperatures) are used as predictors to identify which parts of the series are linked to a single outcome. Together, these FDA models offer complementary insights, allowing either for predicting a scalar outcome from curves or understanding how scalar predictors influence entire functions [@ramsay2005functional].\n\nInitially applied in plant pathology to study the relationship between Fusarium head blight outbreaks and weather variables over time (using the function-on-scalar model) [@shah2019a], FDA has since been adopted in other plant pathology studies with similar objectives [@shah2019; @hjelkrem2021a; @alves2022a].\n\nIn particular, @shah2019 used FDA as a basis to develop logistic regression models for large-scale deployment by utilizing FDA through a scalar-on-function approach to predict plant diseases - in this approach, the model identifies which parts of the time series (e.g., certain weeks or days) are most associated with the disease outcome, helping to predict whether an epidemic is likely to occur based on patterns in the weather series. Moreover, FDA was employed to identify the most relevant temporal regions of weather series associated with disease outbreaks, improving prediction by summarizing key windows across critical growth stages. The authors discussed that, unlike traditional window-pane analysis, FDA reduces statistical testing issues and offers a more refined method for incorporating novel predictors into simple, effective models [@shah2019].\n\nWith the objective of identifying temporal regions of the weather series, Alves et al. (unpublished) proposed the use of a function-on-scalar model to gain insights about the time series related to a binary disease outcome by identifying significant regions in the weather series where the curves diverge. The function-on-scalar approach here compares the average functional trajectories of two groups: epidemic vs. non-epidemic. It identifies time regions where the mean weather curves for the two groups differ significantly. While the model doesn't directly predict a binary response, it aids in diagnosing critical time points in the series that differentiate the two disease outcomes, supporting model development and refinement for binary classification.\n\nFor that purpose, the authors used the `ITP2bspline()` function of the R package {fdatest} that implements the Interval Testing Procedure (ITP) to compare two functional populations (epidemic vs. non-epidemic) evaluated on a uniform grid. It represents data using B-spline basis functions and assesses the significance of each basis coefficient with interval-wise control of the family-wise error rate (FWER) [@pini2016].\n\nIn this section, we first demonstrate how to fit the function-on-scalar regression with the objective of visualizing two curves, the difference coefficient function and the overall mean coefficient curve. The former shows how the effect of a weather-related variable on the response variable changes over the days relative to a reference date (e.g. planting date, flowering). It helps to identify critical windows when the weather variations have the most substantial impact. The latter is the mean weather curve of the reference group (non-epidemic studies); the difference coefficient is the difference between the mean curves of epidemic and non-epidemic studies.\n\nThen, we demonstrate the Interval Testing Procedure (ITP) to compare two functional populations (epidemic vs. non-epidemic) and identify exactly the days in the series that the two populations are significantly different. We will keep analyzing the data on wheat blast epidemics in Brazil.\n\n##### Function-on-scalar regression\n\nThe following analysis uses function-on-scalar regression to explore the relationship between relative humidity at 2 meters (RH2M) and the occurrence of wheat blast epidemics. Let's first load the necessary libraries.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(dplyr)\nlibrary(tidyr)\nlibrary(r4pde)\nlibrary(refund)\nlibrary(ggplot2)\n```\n:::\n\n\nThe first step involves reading and merging two datasets:\n\n\\- `trials`: Contains disease data with heading dates.\n\n\\- `weather_data`: Contains weather data for specific time windows. It was created in the previous section on window-pane and can be downloaded [here](https://raw.githubusercontent.com/emdelponte/epidemiology-R/refs/heads/main/data/weather_windowpane.csv).\n\nThe datasets are merged into `trials_weather`, and the resulting data is transformed into a wide format where each column represents time points (days), and rows correspond to individual studies. The binary epidemic status is created, where:\n\n-   1 indicates an epidemic (if `inc_mean > 20`).\n-   0 indicates no epidemic (if `inc_mean <= 20`).\n\nThe weather variable (`RH2M`) is used as the predictor, and time points (days) are calculated relative to the heading date.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# load the disease dataset\ntrials <- r4pde::BlastWheat\ntrials$heading = as.Date(trials$heading, format = \"%d-%m-%Y\")\n\n# load the weather data constructed in previous section\nweather_data <- readr::read_csv(\"https://raw.githubusercontent.com/emdelponte/epidemiology-R/refs/heads/main/data/weather_windowpane.csv\")\ntrials_weather <- full_join(trials, weather_data)\n\n# create epidemic variable and number of days relative to heading\ndat_wide_RH <- trials_weather |>\n    mutate(epidemic = if_else(inc_mean > 20, 1, 0),\n           days = as.numeric(-(heading - YYYYMMDD))) |>\n    dplyr::select(study, epidemic, days, RH2M) |>\n    pivot_wider(id_cols = c(study, epidemic), \n                names_from = days, values_from = RH2M)\n```\n:::\n\n\nThe scalar covariate is the epidemic status (0 or 1), while the functional response is a matrix with the values of the specified weather variable across time (one row per study, one column per day). The model fits smooth functions to represent the effects of time and the epidemic status on the weather variable using penalized splines. The function-on-scalar regression model is given by:\n\n$y_{ij} = \\beta_0(t_j) + \\beta_1(t_j) x_i + \\epsilon_{ij}$\n\nwhere: $y_{ij}$ is the value of the weather variable for study $i$ at time $j$; $\\beta_0(t_j)$ is the smooth function for the overall mean effect over time; $\\beta_1(t_j)$ is the smooth function representing the effect of epidemic status over time; $x_i$ is the binary epidemic status (0 or 1); and $\\epsilon{ij}$ is the error term.\n\nWe can now fit the model using the `pffr()` function of the {refund} package.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx <- dat_wide_RH$epidemic  # Scalar covariate (epidemic status)\ny <- dat_wide_RH |> \n  dplyr::select(-study, -epidemic) |> \n  as.matrix()  # Functional response (weather variable by day)\n\nyind <- as.numeric(colnames(y))\n\nFOSR_RH <- pffr(y ~ x, \n             yind = yind,\n             bs.yindex = list(bs = \"ps\", k = 30, m = c(2, 1)), \n             bs.int = list(bs = \"ps\", k = 30, m = c(2, 1)),\n                algorithm = \"gam\")\n```\n:::\n\n\nLet's extract the coefficients of the model fit object and prepare the data and plot using ggplot.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n  coef_list <- coef(FOSR_RH)$smterms\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nusing seWithMean for  s(yind.vec) .\n```\n\n\n:::\n\n```{.r .cell-code}\n  mean_df <- data.frame(\n    time = coef_list[[1]]$coef[, \"yind.vec\"],\n    value = coef_list[[1]]$coef[, \"value\"],\n    lower = coef_list[[1]]$coef[, \"value\"] - 1.96 * coef_list[[1]]$coef[, \"se\"],\n    upper = coef_list[[1]]$coef[, \"value\"] + 1.96 * coef_list[[1]]$coef[, \"se\"],\n    term = \"Overall Mean\"\n  )\n  \n  x_df <- data.frame(\n    time = coef_list[[2]]$coef[, \"yind.vec\"],\n    value = coef_list[[2]]$coef[, \"value\"],\n    lower = coef_list[[2]]$coef[, \"value\"] - 1.96 * coef_list[[2]]$coef[, \"se\"],\n    upper = coef_list[[2]]$coef[, \"value\"] + 1.96 * coef_list[[2]]$coef[, \"se\"],\n    term = \"Difference\"\n  )\n  \n  plot_df <- bind_rows(mean_df, x_df)\n  \n\n  ggplot(plot_df, aes(x = time, y = value)) +\n    geom_ribbon(aes(ymin = lower, ymax = upper), \n                alpha = 0.2) +\n    geom_line(linewidth = 1.2) +\n    facet_grid(rows = vars(term), \n               scales = \"free_y\") +\n    theme_r4pde(font_size = 12) +\n    geom_hline(aes(yintercept = 0), \n               color = \"grey\", \n               linetype = \"dashed\") +\n    geom_vline(aes(xintercept = 0), \n               color = \"grey\", \n               linetype = \"dashed\") +\n    labs(x = \"Day relative to wheat heading\", y = \"Coefficient Function\",\n         title = \"RH2M\") +\n    theme(strip.text = element_text(face = \"bold\", size = rel(1.0)),\n          axis.title = element_text(face = \"bold\", size = 12))\n```\n\n::: {.cell-output-display}\n![Function-on-scalar regression for relative humidity: overall mean curve and difference between epidemic and non-epidemic studies, with 95% confidence bands](prediction-disease-modeling_files/figure-html/fig-fosr-rh-1.png){#fig-fosr-rh width=672}\n:::\n:::\n\n\nBecause we have several weather variables, we can facilitate the process by creating a function named `fosr()` that can be applied for the other variables.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Define the function for function-on-scalar regression\nfosr <- function(data, weather_var) {\n  \n  # Step 1: Prepare the dataset and transform to wide format\n  dat_wide <- data |>\n    mutate(epidemic = if_else(inc_mean > 20, 1, 0),\n           days = as.numeric(-(heading - YYYYMMDD))) |>\n      dplyr::select(study, epidemic, days, !!sym(weather_var)) |>\n    pivot_wider(id_cols = c(study, epidemic), names_from = days, values_from = !!sym(weather_var))\n  \n\n  x <- dat_wide$epidemic  # Scalar covariate (epidemic status)\n  y <- dat_wide |>\n    dplyr::select(-study, -epidemic) |>\n    as.matrix()  # Functional response (weather variable by day)\n  \n  m2 <- pffr(y ~ x, \n             yind = yind,\n             bs.yindex = list(bs = \"ps\", k = 30, m = c(2, 1)), \n             bs.int = list(bs = \"ps\", k = 30, m = c(2, 1)),\n                algorithm = \"gam\")\n\n  coef_list <- coef(m2)$smterms\n  \n  mean_df <- data.frame(\n    time = coef_list[[1]]$coef[, \"yind.vec\"],\n    value = coef_list[[1]]$coef[, \"value\"],\n    lower = coef_list[[1]]$coef[, \"value\"] - 1.96 * coef_list[[1]]$coef[, \"se\"],\n    upper = coef_list[[1]]$coef[, \"value\"] + 1.96 * coef_list[[1]]$coef[, \"se\"],\n    term = \"Overall Mean\"\n  )\n  \n  x_df <- data.frame(\n    time = coef_list[[2]]$coef[, \"yind.vec\"],\n    value = coef_list[[2]]$coef[, \"value\"],\n    lower = coef_list[[2]]$coef[, \"value\"] - 1.96 * coef_list[[2]]$coef[, \"se\"],\n    upper = coef_list[[2]]$coef[, \"value\"] + 1.96 * coef_list[[2]]$coef[, \"se\"],\n    term = \"Difference\"\n  )\n  \n  plot_df <- bind_rows(mean_df, x_df)\n  \n   ggplot(plot_df, aes(x = time, y = value)) +\n    geom_ribbon(aes(ymin = lower, ymax = upper), \n                alpha = 0.2) +\n    geom_line(linewidth = 1.2) +\n    facet_grid(rows = vars(term), \n               scales = \"free_y\") +\n    theme_r4pde(font_size = 10) +\n    geom_hline(aes(yintercept = 0), \n               color = \"grey\", \n               linetype = \"dashed\") +\n    geom_vline(aes(xintercept = 0), \n               color = \"grey\", \n               linetype = \"dashed\") +\n    labs(x = \"Day relative to wheat heading\", y = \"Coefficient Function\",\n         title = weather_var) +\n    theme(strip.text = element_text(face = \"bold\", size = rel(1.0)),\n          axis.title = element_text(face = \"bold\", size = 10))\n}\n```\n:::\n\n\nNow we can apply the function to the other variables and obtain plots for each variable.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntmin <- fosr(trials_weather, \"T2M_MIN\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nusing seWithMean for  s(yind.vec) .\n```\n\n\n:::\n\n```{.r .cell-code}\ntmax <- fosr(trials_weather, \"T2M_MAX\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nusing seWithMean for  s(yind.vec) .\n```\n\n\n:::\n\n```{.r .cell-code}\nrh <- fosr(trials_weather, \"RH2M\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nusing seWithMean for  s(yind.vec) .\n```\n\n\n:::\n\n```{.r .cell-code}\nprec <- fosr(trials_weather, \"PRECTOTCORR\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nusing seWithMean for  s(yind.vec) .\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(patchwork)\n\n(tmin |tmax)/(rh | prec)\n```\n\n::: {.cell-output-display}\n![Function-on-scalar regression coefficient functions for minimum temperature, maximum temperature, relative humidity and precipitation](prediction-disease-modeling_files/figure-html/fig-fosr-all-1.png){#fig-fosr-all width=672}\n:::\n:::\n\n\n##### Interval test procedure\n\nFor this test, we need to subset the data into two epidemic conditions, transform from long to wide format and create a matrix object.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf_epidemic <- trials_weather |> \n  mutate(epidemic = if_else(inc_mean > 20, 1, 0),\n           days = as.numeric(-(heading - YYYYMMDD))) |>\n  filter(epidemic == 1) |> \n  dplyr::select(RH2M, days, study)\n\ndf_non_epidemic <- trials_weather |> \n   mutate(epidemic = if_else(inc_mean > 20, 1, 0),\n           days = as.numeric(-(heading - YYYYMMDD))) |>\n  filter(epidemic == 0) |> \n  dplyr::select(RH2M, days, study)\n\n# Pivot data to wide format for FDA\ndf_epidemic_wide <- df_epidemic |>\n  group_by(study) |>\n  pivot_wider(names_from = days, values_from = RH2M) |>\n  ungroup() |>\n  dplyr::select(-study)\n\ndf_non_epidemic_wide <- df_non_epidemic |>\n  group_by(study) |>\n  pivot_wider(names_from = days, values_from = RH2M) |>\n  ungroup() |>\n  dplyr::select(-study)\n\n# Convert to matrix\ndata_epidemic <- as.matrix(df_epidemic_wide)\ndata_non_epidemic <- as.matrix(df_non_epidemic_wide)\n```\n:::\n\n\nNow we can apply the function specifying each new data in each data argument.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(fdatest)\n\n# Perform FDA test\nitp_result <- ITP2bspline(data1 = data_epidemic, \n                          data2 = data_non_epidemic, \n                          B = 100)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"First step: basis expansion\"\nSwapping 'y' and 'argvals', because 'y' is  simpler,\n  and 'argvals' should be;  now  dim(argvals) =  57 ;  dim(y) =  57 x 143 \n[1] \"Second step: joint univariate tests\"\n[1] \"Third step: interval-wise combination and correction\"\n[1] \"creating the p-value matrix: end of row 2 out of 57\"\n[1] \"creating the p-value matrix: end of row 3 out of 57\"\n[1] \"creating the p-value matrix: end of row 4 out of 57\"\n[1] \"creating the p-value matrix: end of row 5 out of 57\"\n[1] \"creating the p-value matrix: end of row 6 out of 57\"\n[1] \"creating the p-value matrix: end of row 7 out of 57\"\n[1] \"creating the p-value matrix: end of row 8 out of 57\"\n[1] \"creating the p-value matrix: end of row 9 out of 57\"\n[1] \"creating the p-value matrix: end of row 10 out of 57\"\n[1] \"creating the p-value matrix: end of row 11 out of 57\"\n[1] \"creating the p-value matrix: end of row 12 out of 57\"\n[1] \"creating the p-value matrix: end of row 13 out of 57\"\n[1] \"creating the p-value matrix: end of row 14 out of 57\"\n[1] \"creating the p-value matrix: end of row 15 out of 57\"\n[1] \"creating the p-value matrix: end of row 16 out of 57\"\n[1] \"creating the p-value matrix: end of row 17 out of 57\"\n[1] \"creating the p-value matrix: end of row 18 out of 57\"\n[1] \"creating the p-value matrix: end of row 19 out of 57\"\n[1] \"creating the p-value matrix: end of row 20 out of 57\"\n[1] \"creating the p-value matrix: end of row 21 out of 57\"\n[1] \"creating the p-value matrix: end of row 22 out of 57\"\n[1] \"creating the p-value matrix: end of row 23 out of 57\"\n[1] \"creating the p-value matrix: end of row 24 out of 57\"\n[1] \"creating the p-value matrix: end of row 25 out of 57\"\n[1] \"creating the p-value matrix: end of row 26 out of 57\"\n[1] \"creating the p-value matrix: end of row 27 out of 57\"\n[1] \"creating the p-value matrix: end of row 28 out of 57\"\n[1] \"creating the p-value matrix: end of row 29 out of 57\"\n[1] \"creating the p-value matrix: end of row 30 out of 57\"\n[1] \"creating the p-value matrix: end of row 31 out of 57\"\n[1] \"creating the p-value matrix: end of row 32 out of 57\"\n[1] \"creating the p-value matrix: end of row 33 out of 57\"\n[1] \"creating the p-value matrix: end of row 34 out of 57\"\n[1] \"creating the p-value matrix: end of row 35 out of 57\"\n[1] \"creating the p-value matrix: end of row 36 out of 57\"\n[1] \"creating the p-value matrix: end of row 37 out of 57\"\n[1] \"creating the p-value matrix: end of row 38 out of 57\"\n[1] \"creating the p-value matrix: end of row 39 out of 57\"\n[1] \"creating the p-value matrix: end of row 40 out of 57\"\n[1] \"creating the p-value matrix: end of row 41 out of 57\"\n[1] \"creating the p-value matrix: end of row 42 out of 57\"\n[1] \"creating the p-value matrix: end of row 43 out of 57\"\n[1] \"creating the p-value matrix: end of row 44 out of 57\"\n[1] \"creating the p-value matrix: end of row 45 out of 57\"\n[1] \"creating the p-value matrix: end of row 46 out of 57\"\n[1] \"creating the p-value matrix: end of row 47 out of 57\"\n[1] \"creating the p-value matrix: end of row 48 out of 57\"\n[1] \"creating the p-value matrix: end of row 49 out of 57\"\n[1] \"creating the p-value matrix: end of row 50 out of 57\"\n[1] \"creating the p-value matrix: end of row 51 out of 57\"\n[1] \"creating the p-value matrix: end of row 52 out of 57\"\n[1] \"creating the p-value matrix: end of row 53 out of 57\"\n[1] \"creating the p-value matrix: end of row 54 out of 57\"\n[1] \"creating the p-value matrix: end of row 55 out of 57\"\n[1] \"creating the p-value matrix: end of row 56 out of 57\"\n[1] \"creating the p-value matrix: end of row 57 out of 57\"\n[1] \"Interval Testing Procedure completed\"\n```\n\n\n:::\n:::\n\n\nHere, we can see the p-values for each time point as well as which time points were significant considering p \\< 0.05.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# global p-values\nitp_result$corrected.pval\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0\n[39] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0\n```\n\n\n:::\n\n```{.r .cell-code}\n# significant components\nwhich(itp_result$corrected.pval < 0.05)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25\n[26] 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50\n[51] 51 52 53 54 55 56 57\n```\n\n\n:::\n:::\n\n\nThe plot function produces two graphs, one for the curves and another for the p-values where the shaded area indicates the significance.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Plot FDA results\nplot(itp_result, main = \"RH2M\", \n     xrange = c(-28, 28), \n     xlab = 'Day', xaxt = 'n')\n```\n\n::: {.cell-output-display}\n![](prediction-disease-modeling_files/figure-html/unnamed-chunk-40-1.png){width=672}\n:::\n\n```{.r .cell-code}\naxis(1, at = seq(-28, 28, by = 2), \n     labels = seq(-28, 28, by = 2))\n```\n\n::: {.cell-output-display}\n![](prediction-disease-modeling_files/figure-html/unnamed-chunk-40-2.png){width=672}\n:::\n:::\n\n\nBecause we may have several weather variables, we can avoid repeating the code for each variable by creating a function. The arguments are the data and weather variable. Optionally, the user can define the threshold for disease.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrun_ITP_test <- function(data, weather_var, threshold = 20, B = 100) {\n  \n  # Convert the weather_var input to symbol for dplyr's select function\n  weather_var_sym <- sym(weather_var)\n  \n  # Filter and prepare epidemic data\n  df_epidemic <- data |> \n    mutate(epidemic = if_else(inc_mean > threshold, 1, 0),\n           days = as.numeric(-(heading - YYYYMMDD))) |> \n    filter(epidemic == 1) |> \n    dplyr::select(!!weather_var_sym, days, study)\n  \n  # Filter and prepare non-epidemic data\n  df_non_epidemic <- data |> \n    mutate(epidemic = if_else(inc_mean > threshold, 1, 0),\n           days = as.numeric(-(heading - YYYYMMDD))) |> \n    filter(epidemic == 0) |> \n    dplyr::select(!!weather_var_sym, days, study)\n  \n  # Pivot epidemic data to wide format\n  df_epidemic_wide <- df_epidemic |> \n    group_by(study) |> \n    pivot_wider(names_from = days, values_from = !!weather_var_sym) |> \n    ungroup() |> \n    dplyr::select(-study)\n  \n  # Pivot non-epidemic data to wide format\n  df_non_epidemic_wide <- df_non_epidemic |> \n    group_by(study) |> \n    pivot_wider(names_from = days, values_from = !!weather_var_sym) |> \n    ungroup() |> \n    dplyr::select(-study)\n  \n  # Convert to matrix\n  data_epidemic <- as.matrix(df_epidemic_wide)\n  data_non_epidemic <- as.matrix(df_non_epidemic_wide)\n  \n  # Perform FDA test\n  itp_result <- ITP2bspline(data1 = data_epidemic, \n                            data2 = data_non_epidemic, \n                            B = B)\n  \n  return(itp_result)\n}\n```\n:::\n\n\nApplying the function to each variable.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nitp_tmin <- run_ITP_test(data = trials_weather, weather_var = \"T2M_MIN\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"First step: basis expansion\"\nSwapping 'y' and 'argvals', because 'y' is  simpler,\n  and 'argvals' should be;  now  dim(argvals) =  57 ;  dim(y) =  57 x 143 \n[1] \"Second step: joint univariate tests\"\n[1] \"Third step: interval-wise combination and correction\"\n[1] \"creating the p-value matrix: end of row 2 out of 57\"\n[1] \"creating the p-value matrix: end of row 3 out of 57\"\n[1] \"creating the p-value matrix: end of row 4 out of 57\"\n[1] \"creating the p-value matrix: end of row 5 out of 57\"\n[1] \"creating the p-value matrix: end of row 6 out of 57\"\n[1] \"creating the p-value matrix: end of row 7 out of 57\"\n[1] \"creating the p-value matrix: end of row 8 out of 57\"\n[1] \"creating the p-value matrix: end of row 9 out of 57\"\n[1] \"creating the p-value matrix: end of row 10 out of 57\"\n[1] \"creating the p-value matrix: end of row 11 out of 57\"\n[1] \"creating the p-value matrix: end of row 12 out of 57\"\n[1] \"creating the p-value matrix: end of row 13 out of 57\"\n[1] \"creating the p-value matrix: end of row 14 out of 57\"\n[1] \"creating the p-value matrix: end of row 15 out of 57\"\n[1] \"creating the p-value matrix: end of row 16 out of 57\"\n[1] \"creating the p-value matrix: end of row 17 out of 57\"\n[1] \"creating the p-value matrix: end of row 18 out of 57\"\n[1] \"creating the p-value matrix: end of row 19 out of 57\"\n[1] \"creating the p-value matrix: end of row 20 out of 57\"\n[1] \"creating the p-value matrix: end of row 21 out of 57\"\n[1] \"creating the p-value matrix: end of row 22 out of 57\"\n[1] \"creating the p-value matrix: end of row 23 out of 57\"\n[1] \"creating the p-value matrix: end of row 24 out of 57\"\n[1] \"creating the p-value matrix: end of row 25 out of 57\"\n[1] \"creating the p-value matrix: end of row 26 out of 57\"\n[1] \"creating the p-value matrix: end of row 27 out of 57\"\n[1] \"creating the p-value matrix: end of row 28 out of 57\"\n[1] \"creating the p-value matrix: end of row 29 out of 57\"\n[1] \"creating the p-value matrix: end of row 30 out of 57\"\n[1] \"creating the p-value matrix: end of row 31 out of 57\"\n[1] \"creating the p-value matrix: end of row 32 out of 57\"\n[1] \"creating the p-value matrix: end of row 33 out of 57\"\n[1] \"creating the p-value matrix: end of row 34 out of 57\"\n[1] \"creating the p-value matrix: end of row 35 out of 57\"\n[1] \"creating the p-value matrix: end of row 36 out of 57\"\n[1] \"creating the p-value matrix: end of row 37 out of 57\"\n[1] \"creating the p-value matrix: end of row 38 out of 57\"\n[1] \"creating the p-value matrix: end of row 39 out of 57\"\n[1] \"creating the p-value matrix: end of row 40 out of 57\"\n[1] \"creating the p-value matrix: end of row 41 out of 57\"\n[1] \"creating the p-value matrix: end of row 42 out of 57\"\n[1] \"creating the p-value matrix: end of row 43 out of 57\"\n[1] \"creating the p-value matrix: end of row 44 out of 57\"\n[1] \"creating the p-value matrix: end of row 45 out of 57\"\n[1] \"creating the p-value matrix: end of row 46 out of 57\"\n[1] \"creating the p-value matrix: end of row 47 out of 57\"\n[1] \"creating the p-value matrix: end of row 48 out of 57\"\n[1] \"creating the p-value matrix: end of row 49 out of 57\"\n[1] \"creating the p-value matrix: end of row 50 out of 57\"\n[1] \"creating the p-value matrix: end of row 51 out of 57\"\n[1] \"creating the p-value matrix: end of row 52 out of 57\"\n[1] \"creating the p-value matrix: end of row 53 out of 57\"\n[1] \"creating the p-value matrix: end of row 54 out of 57\"\n[1] \"creating the p-value matrix: end of row 55 out of 57\"\n[1] \"creating the p-value matrix: end of row 56 out of 57\"\n[1] \"creating the p-value matrix: end of row 57 out of 57\"\n[1] \"Interval Testing Procedure completed\"\n```\n\n\n:::\n\n```{.r .cell-code}\nitp_tmax <- run_ITP_test(data = trials_weather, weather_var = \"T2M_MAX\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"First step: basis expansion\"\nSwapping 'y' and 'argvals', because 'y' is  simpler,\n  and 'argvals' should be;  now  dim(argvals) =  57 ;  dim(y) =  57 x 143 \n[1] \"Second step: joint univariate tests\"\n[1] \"Third step: interval-wise combination and correction\"\n[1] \"creating the p-value matrix: end of row 2 out of 57\"\n[1] \"creating the p-value matrix: end of row 3 out of 57\"\n[1] \"creating the p-value matrix: end of row 4 out of 57\"\n[1] \"creating the p-value matrix: end of row 5 out of 57\"\n[1] \"creating the p-value matrix: end of row 6 out of 57\"\n[1] \"creating the p-value matrix: end of row 7 out of 57\"\n[1] \"creating the p-value matrix: end of row 8 out of 57\"\n[1] \"creating the p-value matrix: end of row 9 out of 57\"\n[1] \"creating the p-value matrix: end of row 10 out of 57\"\n[1] \"creating the p-value matrix: end of row 11 out of 57\"\n[1] \"creating the p-value matrix: end of row 12 out of 57\"\n[1] \"creating the p-value matrix: end of row 13 out of 57\"\n[1] \"creating the p-value matrix: end of row 14 out of 57\"\n[1] \"creating the p-value matrix: end of row 15 out of 57\"\n[1] \"creating the p-value matrix: end of row 16 out of 57\"\n[1] \"creating the p-value matrix: end of row 17 out of 57\"\n[1] \"creating the p-value matrix: end of row 18 out of 57\"\n[1] \"creating the p-value matrix: end of row 19 out of 57\"\n[1] \"creating the p-value matrix: end of row 20 out of 57\"\n[1] \"creating the p-value matrix: end of row 21 out of 57\"\n[1] \"creating the p-value matrix: end of row 22 out of 57\"\n[1] \"creating the p-value matrix: end of row 23 out of 57\"\n[1] \"creating the p-value matrix: end of row 24 out of 57\"\n[1] \"creating the p-value matrix: end of row 25 out of 57\"\n[1] \"creating the p-value matrix: end of row 26 out of 57\"\n[1] \"creating the p-value matrix: end of row 27 out of 57\"\n[1] \"creating the p-value matrix: end of row 28 out of 57\"\n[1] \"creating the p-value matrix: end of row 29 out of 57\"\n[1] \"creating the p-value matrix: end of row 30 out of 57\"\n[1] \"creating the p-value matrix: end of row 31 out of 57\"\n[1] \"creating the p-value matrix: end of row 32 out of 57\"\n[1] \"creating the p-value matrix: end of row 33 out of 57\"\n[1] \"creating the p-value matrix: end of row 34 out of 57\"\n[1] \"creating the p-value matrix: end of row 35 out of 57\"\n[1] \"creating the p-value matrix: end of row 36 out of 57\"\n[1] \"creating the p-value matrix: end of row 37 out of 57\"\n[1] \"creating the p-value matrix: end of row 38 out of 57\"\n[1] \"creating the p-value matrix: end of row 39 out of 57\"\n[1] \"creating the p-value matrix: end of row 40 out of 57\"\n[1] \"creating the p-value matrix: end of row 41 out of 57\"\n[1] \"creating the p-value matrix: end of row 42 out of 57\"\n[1] \"creating the p-value matrix: end of row 43 out of 57\"\n[1] \"creating the p-value matrix: end of row 44 out of 57\"\n[1] \"creating the p-value matrix: end of row 45 out of 57\"\n[1] \"creating the p-value matrix: end of row 46 out of 57\"\n[1] \"creating the p-value matrix: end of row 47 out of 57\"\n[1] \"creating the p-value matrix: end of row 48 out of 57\"\n[1] \"creating the p-value matrix: end of row 49 out of 57\"\n[1] \"creating the p-value matrix: end of row 50 out of 57\"\n[1] \"creating the p-value matrix: end of row 51 out of 57\"\n[1] \"creating the p-value matrix: end of row 52 out of 57\"\n[1] \"creating the p-value matrix: end of row 53 out of 57\"\n[1] \"creating the p-value matrix: end of row 54 out of 57\"\n[1] \"creating the p-value matrix: end of row 55 out of 57\"\n[1] \"creating the p-value matrix: end of row 56 out of 57\"\n[1] \"creating the p-value matrix: end of row 57 out of 57\"\n[1] \"Interval Testing Procedure completed\"\n```\n\n\n:::\n\n```{.r .cell-code}\nitp_prec <- run_ITP_test(data = trials_weather, weather_var = \"PRECTOTCORR\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"First step: basis expansion\"\nSwapping 'y' and 'argvals', because 'y' is  simpler,\n  and 'argvals' should be;  now  dim(argvals) =  57 ;  dim(y) =  57 x 143 \n[1] \"Second step: joint univariate tests\"\n[1] \"Third step: interval-wise combination and correction\"\n[1] \"creating the p-value matrix: end of row 2 out of 57\"\n[1] \"creating the p-value matrix: end of row 3 out of 57\"\n[1] \"creating the p-value matrix: end of row 4 out of 57\"\n[1] \"creating the p-value matrix: end of row 5 out of 57\"\n[1] \"creating the p-value matrix: end of row 6 out of 57\"\n[1] \"creating the p-value matrix: end of row 7 out of 57\"\n[1] \"creating the p-value matrix: end of row 8 out of 57\"\n[1] \"creating the p-value matrix: end of row 9 out of 57\"\n[1] \"creating the p-value matrix: end of row 10 out of 57\"\n[1] \"creating the p-value matrix: end of row 11 out of 57\"\n[1] \"creating the p-value matrix: end of row 12 out of 57\"\n[1] \"creating the p-value matrix: end of row 13 out of 57\"\n[1] \"creating the p-value matrix: end of row 14 out of 57\"\n[1] \"creating the p-value matrix: end of row 15 out of 57\"\n[1] \"creating the p-value matrix: end of row 16 out of 57\"\n[1] \"creating the p-value matrix: end of row 17 out of 57\"\n[1] \"creating the p-value matrix: end of row 18 out of 57\"\n[1] \"creating the p-value matrix: end of row 19 out of 57\"\n[1] \"creating the p-value matrix: end of row 20 out of 57\"\n[1] \"creating the p-value matrix: end of row 21 out of 57\"\n[1] \"creating the p-value matrix: end of row 22 out of 57\"\n[1] \"creating the p-value matrix: end of row 23 out of 57\"\n[1] \"creating the p-value matrix: end of row 24 out of 57\"\n[1] \"creating the p-value matrix: end of row 25 out of 57\"\n[1] \"creating the p-value matrix: end of row 26 out of 57\"\n[1] \"creating the p-value matrix: end of row 27 out of 57\"\n[1] \"creating the p-value matrix: end of row 28 out of 57\"\n[1] \"creating the p-value matrix: end of row 29 out of 57\"\n[1] \"creating the p-value matrix: end of row 30 out of 57\"\n[1] \"creating the p-value matrix: end of row 31 out of 57\"\n[1] \"creating the p-value matrix: end of row 32 out of 57\"\n[1] \"creating the p-value matrix: end of row 33 out of 57\"\n[1] \"creating the p-value matrix: end of row 34 out of 57\"\n[1] \"creating the p-value matrix: end of row 35 out of 57\"\n[1] \"creating the p-value matrix: end of row 36 out of 57\"\n[1] \"creating the p-value matrix: end of row 37 out of 57\"\n[1] \"creating the p-value matrix: end of row 38 out of 57\"\n[1] \"creating the p-value matrix: end of row 39 out of 57\"\n[1] \"creating the p-value matrix: end of row 40 out of 57\"\n[1] \"creating the p-value matrix: end of row 41 out of 57\"\n[1] \"creating the p-value matrix: end of row 42 out of 57\"\n[1] \"creating the p-value matrix: end of row 43 out of 57\"\n[1] \"creating the p-value matrix: end of row 44 out of 57\"\n[1] \"creating the p-value matrix: end of row 45 out of 57\"\n[1] \"creating the p-value matrix: end of row 46 out of 57\"\n[1] \"creating the p-value matrix: end of row 47 out of 57\"\n[1] \"creating the p-value matrix: end of row 48 out of 57\"\n[1] \"creating the p-value matrix: end of row 49 out of 57\"\n[1] \"creating the p-value matrix: end of row 50 out of 57\"\n[1] \"creating the p-value matrix: end of row 51 out of 57\"\n[1] \"creating the p-value matrix: end of row 52 out of 57\"\n[1] \"creating the p-value matrix: end of row 53 out of 57\"\n[1] \"creating the p-value matrix: end of row 54 out of 57\"\n[1] \"creating the p-value matrix: end of row 55 out of 57\"\n[1] \"creating the p-value matrix: end of row 56 out of 57\"\n[1] \"creating the p-value matrix: end of row 57 out of 57\"\n[1] \"Interval Testing Procedure completed\"\n```\n\n\n:::\n\n```{.r .cell-code}\nitp_tmin$corrected.pval\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] 0.00 0.00 0.02 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00\n[16] 0.00 0.00 0.00 0.00 0.00 0.00 0.01 0.00 0.00 0.00 0.00 0.00 0.07 0.12 0.01\n[31] 0.00 0.01 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.18 0.04 0.02\n[46] 0.00 0.00 0.00 0.00 0.01 0.00 0.00 0.00 0.00 0.08 0.06 0.13\n```\n\n\n:::\n\n```{.r .cell-code}\nwhich(itp_tmin$corrected.pval < 0.05)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25\n[26] 26 27 30 31 32 33 34 35 36 37 38 39 40 41 42 44 45 46 47 48 49 50 51 52 53\n[51] 54\n```\n\n\n:::\n\n```{.r .cell-code}\nitp_tmax$corrected.pval\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] 0.00 0.00 0.05 0.18 0.10 0.09 0.04 0.08 0.21 0.51 0.26 0.11 0.00 0.32 0.39\n[16] 0.44 0.43 0.43 0.56 0.32 0.18 0.27 0.28 0.35 0.50 0.49 0.31 0.15 0.10 0.00\n[31] 0.05 0.07 0.07 0.08 0.11 0.18 0.14 0.46 0.20 0.19 0.20 0.20 0.26 0.46 0.35\n[46] 0.29 0.61 0.90 0.95 0.68 0.66 0.66 0.51 0.32 0.00 0.00 0.00\n```\n\n\n:::\n\n```{.r .cell-code}\nwhich(itp_tmax$corrected.pval < 0.05)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1]  1  2  7 13 30 55 56 57\n```\n\n\n:::\n\n```{.r .cell-code}\nitp_prec$corrected.pval\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] 0.00 0.21 0.48 0.09 0.29 0.03 0.00 0.00 0.92 0.07 0.01 0.09 0.00 0.02 0.20\n[16] 0.00 0.01 0.00 0.00 0.37 0.03 0.00 0.00 0.01 0.22 0.03 0.00 0.00 0.00 0.00\n[31] 0.00 0.00 0.00 0.25 0.00 0.00 0.10 0.07 0.02 0.00 0.10 0.20 0.85 0.51 0.40\n[46] 0.51 0.83 0.98 0.98 0.98 0.43 0.23 0.00 0.01 0.00 0.07 0.03\n```\n\n\n:::\n\n```{.r .cell-code}\nwhich(itp_prec$corrected.pval < 0.05)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1]  1  6  7  8 11 13 14 16 17 18 19 21 22 23 24 26 27 28 29 30 31 32 33 35 36\n[26] 39 40 53 54 55 57\n```\n\n\n:::\n\n```{.r .cell-code}\nplot(itp_tmin, main = \"TMIN\", \n     xrange = c(-28, 28), \n     xlab = 'Day', xaxt = 'n')\n```\n\n::: {.cell-output-display}\n![](prediction-disease-modeling_files/figure-html/unnamed-chunk-42-1.png){width=672}\n:::\n\n```{.r .cell-code}\naxis(1, at = seq(-28, 28, by = 2), \n     labels = seq(-28, 28, by = 2))\n```\n\n::: {.cell-output-display}\n![](prediction-disease-modeling_files/figure-html/unnamed-chunk-42-2.png){width=672}\n:::\n\n```{.r .cell-code}\nplot(itp_tmax, main = \"TMAX\", \n     xrange = c(-28, 28), \n     xlab = 'Day', xaxt = 'n')\n```\n\n::: {.cell-output-display}\n![](prediction-disease-modeling_files/figure-html/unnamed-chunk-42-3.png){width=672}\n:::\n\n```{.r .cell-code}\naxis(1, at = seq(-28, 28, by = 2), \n     labels = seq(-28, 28, by = 2))\n```\n\n::: {.cell-output-display}\n![](prediction-disease-modeling_files/figure-html/unnamed-chunk-42-4.png){width=672}\n:::\n\n```{.r .cell-code}\nplot(itp_prec, main = \"PREC\", \n     xrange = c(-28, 28), \n     xlab = 'Day', xaxt = 'n')\n```\n\n::: {.cell-output-display}\n![](prediction-disease-modeling_files/figure-html/unnamed-chunk-42-5.png){width=672}\n:::\n\n```{.r .cell-code}\naxis(1, at = seq(-28, 28, by = 2), \n     labels = seq(-28, 28, by = 2))\n```\n\n::: {.cell-output-display}\n![](prediction-disease-modeling_files/figure-html/unnamed-chunk-42-6.png){width=672}\n:::\n:::\n\n\n**Interpretation**: Based on the results above, relative humidity differed significantly between epidemic and non-epidemic studies on every day of the series, and minimum temperature on most days, particularly during the pre-heading period. Maximum temperature differed only on a few isolated days. Lastly, precipitation influenced wheat blast during several short intervals, with the most notable impact occurring over a longer seven-day period around the heading stage. Therefore, TMIN, RH and PREC can be tested further as candidate predictors in prediction models.\n\n### Model fitting\n\n#### Logistic regression models\n\nLogistic regression is a statistical modeling technique used to predict the probability of a binary outcome based on one or more predictor variables [@james2021]. In the context of plant disease prediction, the logistic model relates factors like environmental conditions (usually weather), host characteristics (e.g., cultivar resistance), and pathogen presence to the likelihood of disease occurrence. This occurrence can be expressed as presence or absence [@mila2004] or as a classification of incidence/severity based on an epidemic threshold [@dewolf2003; @decól2024]. By integrating these variables, the model enables researchers to assess disease risk under varying conditions and to develop decision support systems. This modeling approach has been used successfully in several studies in the field [@harikrishnan2008; @xu2013; @romero2021; @shah2013; @mila2004; @decól2024; @willbur2018; @dewolf2003], demonstrating its efficacy in predicting disease outbreaks and informing early intervention efforts.\n\nThe logistic model uses the logistic function to transform a linear combination of predictors into a probability between 0 and 1. This transformation ensures that the predicted values are valid probabilities, facilitating meaningful interpretations. By estimating the influence of each predictor on the odds of disease, logistic regression helps identify significant risk factors. Additionally, the model's coefficients provide insights into the strength and direction of the association between predictors and disease risk, offering valuable information for understanding the underlying mechanisms of disease development and progression.\n\nThe logistic regression model predicts the probability $P$ of the binary outcome $Y = 1 \\mid X$ (e.g., presence or absence of disease) given a set of predictor variables $X$. The model uses the logistic function to ensure the predicted probabilities lie between 0 and 1:\n\n$P(Y = 1 \\mid X) = \\frac{1}{1 + e^{-(\\beta_0 + \\beta_1 X_1 + \\beta_2 X_2 + \\dots + \\beta_p X_p)}}$\n\nAlternatively, the model can be expressed in terms of the log-odds (also known as the logit function):\n\n$\\log\\left( \\frac{P(Y = 1 \\mid X)}{1 - P(Y = 1 \\mid X)} \\right) = \\beta_0 + \\beta_1 X_1 + \\beta_2 X_2 + \\dots + \\beta_p X_p$\n\nCompared to more complex machine learning models, logistic regression offers a high degree of interpretability, which is crucial in many scientific and practical applications. While models like neural networks, random forests, or support vector machines can achieve high predictive accuracy, they often function as \"black boxes\" where the relationship between predictors and the outcome is not easily understood [@molnar2019]. In contrast, logistic regression provides clear and direct interpretations of model parameters, allowing researchers and practitioners to understand how each predictor variable influences the probability of disease occurrence. This transparency makes logistic regression a preferred choice in contexts where explaining the underlying relationships is as important as prediction accuracy. The balance between interpretability and predictive performance justifies the choice of logistic regression in several contexts, especially when insights into the data are essential for decision-making, which is the case in plant disease prediction contexts.\n\nIn this section, we will keep working with the wheat blast disease data and expand on the previous sections on variable construction and selection, a usual step prior to testing the prediction variables in the logistic regression model.\n\n##### Data preparation\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(r4pde)\nlibrary(tidyverse)\n\n# load the disease dataset\ntrials <- r4pde::BlastWheat\ntrials$heading = as.Date(trials$heading, format = \"%d-%m-%Y\")\n\n# load the weather data \nweather_data <- readr::read_csv(\"https://raw.githubusercontent.com/emdelponte/epidemiology-R/refs/heads/main/data/weather_windowpane.csv\")\n\n# join the two datasets\ntrials_weather <- full_join(trials, weather_data)\n\n# create epidemic variable and number of days relative to heading\ntrials_weather <- trials_weather |>\n    mutate(epidemic = if_else(inc_mean > 20, 1, 0),\n           days = as.numeric(-(heading - YYYYMMDD)))\n```\n:::\n\n\nLet's create a few weather-related variables based on the original variables available from the NASA POWER. First, we need to group by study and epidemic and then filter the days to the period from 28 days before to 7 days after heading, since we will attempt to develop a model using only variables from the period around heading. We will not include mean daily maximum temperature given its weak association based on window-pane and not significant influence based on the interval test procedure of the FDA (see previous section).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nepi_weather <- trials_weather |> \n  group_by(study, epidemic) |> \n  filter(days >= -28 & days <= 7) |> \n  summarise(\n    tmin_pre = mean(T2M_MIN, na.rm = TRUE),\n    rh_pre = mean(RH2M, na.rm = TRUE),\n    prec_pre = sum(PRECTOTCORR, na.rm = TRUE))|> \n  ungroup() |> \n  dplyr::select(- study)\n\n\n## create rainfall around heading\nepi_rain <- trials_weather |> \n  group_by(study, epidemic) |> \n  filter(days >= -3 & days <= 6) |> \n  summarise(\n    prec_pos = sum(PRECTOTCORR, na.rm = TRUE))|> \n  ungroup() |> \n  dplyr::select(- study, - epidemic)\n\nepi_weather2 <- cbind(epi_weather, epi_rain)\n```\n:::\n\n\n##### Model fitting\n\nNow we can fit the model and look at the summary.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# model fitting\nm_logistic <- glm(epidemic ~ tmin_pre + rh_pre + prec_pre, \n                      data = epi_weather, \n                      family = binomial)\n\n# Model summary\nsummary(m_logistic)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = epidemic ~ tmin_pre + rh_pre + prec_pre, family = binomial, \n    data = epi_weather)\n\nCoefficients:\n              Estimate Std. Error z value Pr(>|z|)    \n(Intercept) -18.965637   3.921175  -4.837 1.32e-06 ***\ntmin_pre      0.274067   0.091101   3.008  0.00263 ** \nrh_pre        0.201025   0.047644   4.219 2.45e-05 ***\nprec_pre      0.002652   0.007112   0.373  0.70924    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 197.06  on 142  degrees of freedom\nResidual deviance: 121.55  on 139  degrees of freedom\nAIC: 129.55\n\nNumber of Fisher Scoring iterations: 5\n```\n\n\n:::\n:::\n\n\ninterpretation of the coefficients:\n\n-   Intercept: Estimate of -18.96, indicating the baseline log-odds of an epidemic when all predictors are zero.\n\n-   tmin_pre: Positive estimate (0.27, p = 0.002), indicating that higher minimum temperatures are significantly associated with an increased probability of an epidemic.\n\n-   rh_pre: Positive estimate (0.20, p \\< 0.001), suggesting that higher relative humidity is strongly associated with an increased probability of an epidemic.\n\n-   prec_pre: Positive but non-significant estimate (0.003, p = 0.71), indicating no significant relationship between precipitation and epidemic occurrence.\n\nModel fit\n\n-   The null deviance (197.06) reflects the fit of a model without predictors, while the residual deviance (121.55) indicates the fit of the full model with predictors. A significant reduction in deviance suggests that the predictors improve model fit.\n\n-   The AIC (129.55) helps evaluate model performance, with lower values indicating better fit.\n\nLet's fit again the model using only the two significant variables and include the prec_pos variable.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm_logistic <- glm(epidemic ~ tmin_pre + rh_pre + prec_pos, \n                      data = epi_weather2, \n                      family = binomial)\n\nsummary(m_logistic)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = epidemic ~ tmin_pre + rh_pre + prec_pos, family = binomial, \n    data = epi_weather2)\n\nCoefficients:\n             Estimate Std. Error z value Pr(>|z|)    \n(Intercept) -19.31170    3.47903  -5.551 2.84e-08 ***\ntmin_pre      0.34620    0.10023   3.454 0.000552 ***\nrh_pre        0.18418    0.03746   4.917 8.80e-07 ***\nprec_pos      0.06393    0.02222   2.878 0.004003 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 197.06  on 142  degrees of freedom\nResidual deviance: 109.99  on 139  degrees of freedom\nAIC: 117.99\n\nNumber of Fisher Scoring iterations: 6\n```\n\n\n:::\n:::\n\n\nWe can notice that including rainfall accumulation around flowering, the AIC is reduced to 117.99, suggesting that its inclusion improved prediction.\n\nWe can check the accuracy of the new model in predicting the training data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(caret)\n\n# Obtain the predicted probability\npred_probs <- predict(m_logistic, epi_weather2, type = \"response\")\n\n# Convert probabilities to binary outcomes using 0.5 as the threshold\npred_classes <- ifelse(pred_probs >= 0.5, 1, 0)\n\n# Calculate accuracy\nactual_classes <- epi_weather$epidemic\naccuracy <- mean(pred_classes == actual_classes)\naccuracy\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.8181818\n```\n\n\n:::\n:::\n\n\nThe `confusionMatrix()` function of the {caret} package gives a more complete information about the performance of the model on the training set.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# create the confusion matrix\nconfusionMatrix(data = as.factor(as.numeric(pred_probs > 0.50)),  mode= \"everything\",  reference = as.factor(epi_weather$epidemic),\n                positive = \"1\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nConfusion Matrix and Statistics\n\n          Reference\nPrediction  0  1\n         0 49 10\n         1 16 68\n                                          \n               Accuracy : 0.8182          \n                 95% CI : (0.7451, 0.8777)\n    No Information Rate : 0.5455          \n    P-Value [Acc > NIR] : 6.459e-12       \n                                          \n                  Kappa : 0.6305          \n                                          \n Mcnemar's Test P-Value : 0.3268          \n                                          \n            Sensitivity : 0.8718          \n            Specificity : 0.7538          \n         Pos Pred Value : 0.8095          \n         Neg Pred Value : 0.8305          \n              Precision : 0.8095          \n                 Recall : 0.8718          \n                     F1 : 0.8395          \n             Prevalence : 0.5455          \n         Detection Rate : 0.4755          \n   Detection Prevalence : 0.5874          \n      Balanced Accuracy : 0.8128          \n                                          \n       'Positive' Class : 1               \n                                          \n```\n\n\n:::\n:::\n\n\n##### Model evaluation\n\nIt is highly desirable to evaluate model performance metrics using data that was not \"seen\" by the model during training. If the dataset is sufficiently large (e.g., more than 300 observations), it can be split into training and test sets, typically using an 80:20 ratio. For smaller datasets, alternatives like leave-one-out cross-validation (LOOCV) can be applied, as was done in the original wheat blast model study, which had 143 cases available [@decól2024].\n\nThe Leave-One-Out Cross-Validation (LOOCV) is a resampling method used to evaluate model performance, particularly with small datasets. In LOOCV, the model is trained repeatedly, each time using all but one observation, which is set aside for testing. This process is repeated until every observation has served as the test case once. The overall performance metric is calculated by averaging the results from all iterations, providing an unbiased estimate of model accuracy [@hastie2009].\n\nLet's first create the training and test data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntrain_index <- createDataPartition(epi_weather2$epidemic, p = 0.8, list = FALSE)\ntrain_data <- epi_weather2[train_index, ]\ntest_data <- epi_weather2[-train_index, ]\n```\n:::\n\n\nNow we fit the logistic model on the training data and obtain the predictions.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# fit the model on training data\nm_logistic2 <- glm(epidemic ~ tmin_pre + rh_pre + prec_pos, \n                   data = train_data, \n                   family = binomial)\n\n# Predict on the test data\npred <- predict(m_logistic2, newdata = test_data, type = \"response\")\n```\n:::\n\n\nLet's build now the confusion matrix for the test data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nconfusion_matrix <- confusionMatrix(data = as.factor(as.numeric(pred > 0.5)), reference = as.factor(test_data$epidemic), mode = \"everything\",\n                                   positive = \"1\")\nprint(confusion_matrix)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nConfusion Matrix and Statistics\n\n          Reference\nPrediction  0  1\n         0 12  2\n         1  2 12\n                                          \n               Accuracy : 0.8571          \n                 95% CI : (0.6733, 0.9597)\n    No Information Rate : 0.5             \n    P-Value [Acc > NIR] : 9e-05           \n                                          \n                  Kappa : 0.7143          \n                                          \n Mcnemar's Test P-Value : 1               \n                                          \n            Sensitivity : 0.8571          \n            Specificity : 0.8571          \n         Pos Pred Value : 0.8571          \n         Neg Pred Value : 0.8571          \n              Precision : 0.8571          \n                 Recall : 0.8571          \n                     F1 : 0.8571          \n             Prevalence : 0.5000          \n         Detection Rate : 0.4286          \n   Detection Prevalence : 0.5000          \n      Balanced Accuracy : 0.8571          \n                                          \n       'Positive' Class : 1               \n                                          \n```\n\n\n:::\n:::\n\n\nThe code below provides a comparative evaluation of model accuracy using two different cross-validation techniques, the LOOCV and 10-fold cross validation. The latter is similar to the LOOCV code, but with the addition of `K = 10`, which specifies 10-fold cross-validation. Here, the dataset is divided into 10 subsets (folds), with the model trained on 9 folds and tested on the remaining fold. This process repeats for all 10 folds, averaging the results. For both we need a custom cost function that evaluates the performance of a binary classifier. Note that we will use the model 1 built with all observations, not the training data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(boot)\n\ncost <- function(r, pi = 0) mean(abs(r - pi) > 0.5)\n\n# LOOCV (accuracy)\n1 - cv.glm(epi_weather2, m_logistic, cost = cost)$delta[1]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.8041958\n```\n\n\n:::\n\n```{.r .cell-code}\n# K-fold CV K=10 (accuracy)\n1 - cv.glm(epi_weather2, m_logistic, K = 10, cost = cost)$delta[1]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.8041958\n```\n\n\n:::\n:::\n\n\nWe can conclude that using two variables from relatively long periods before heading, and the precipitation accumulation variable around heading (all defined based on FDA analysis) the model can reasonably predict wheat blast. We can further explore the effect of other variables from the post-heading period, as well as variables from shorter intervals around heading and flowering---periods when infections are likely to occur.\n\nVariable selection is a critical process that combines statistical techniques with biological knowledge to identify the most relevant predictors for a given model. Approaches can range from simple methods, like selecting the most correlated variables at periods of time known as most critical for infection or epidemic development [@dewolf2003], to more advanced algorithms designed to optimize predictive power, such as regularization techniques like lasso or elastic-net [@decól2024; @dallalana2021a; @dewolf2023].\n\nRegularization methods not only help in selecting significant predictors but also in handling multicollinearity and reducing model complexity [@hastie2009].\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"site_libs/htmltools-fill-0.5.8.1/fill.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/htmlwidgets-1.6.4/htmlwidgets.js\"></script>\n<script src=\"site_libs/plotly-binding-4.11.0/plotly.js\"></script>\n<script src=\"site_libs/typedarray-0.1/typedarray.min.js\"></script>\n<script src=\"site_libs/jquery-3.5.1/jquery.min.js\"></script>\n<link href=\"site_libs/crosstalk-1.2.1/css/crosstalk.min.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/crosstalk-1.2.1/js/crosstalk.min.js\"></script>\n<link href=\"site_libs/plotly-htmlwidgets-css-2.11.1/plotly-htmlwidgets.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/plotly-main-2.11.1/plotly-latest.min.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}